import Foundation

/// The web's exported field-capture contract, as read from
/// `Fixtures/field-capture-parity.json`.
///
/// Read the same loose way as `ParityFixture`, and for the same reason:
/// decoded into the Swift types it is checked against, a constant the port
/// models wrongly would round-trip cleanly and pass. The fixture is
/// generated by the web's `captureSpec.test.ts` and must never be
/// regenerated from Swift — it is the independent witness.
public struct FieldCaptureFixture: Sendable {
    public let root: [String: JSONValue]

    public static let loaded: FieldCaptureFixture = {
        guard let url = Bundle.module.url(
            forResource: "field-capture-parity",
            withExtension: "json",
            subdirectory: "Fixtures"
        ) else {
            fatalError("field-capture-parity.json is missing from the test bundle")
        }
        guard let data = try? Data(contentsOf: url),
              let root = try? JSONDecoder().decode([String: JSONValue].self, from: data)
        else {
            fatalError("field-capture-parity.json could not be read as the expected shape")
        }
        return FieldCaptureFixture(root: root)
    }()

    public subscript(key: String) -> JSONValue? {
        root[key]
    }

    /// A nested object, or nil — the test fails on nil rather than skipping,
    /// so a renamed block cannot quietly shrink the comparison.
    public func object(_ key: String) -> [String: JSONValue]? {
        root[key]?.object
    }
}
