import type { ContextLayerDescriptor, ContextFeatureStyle } from "./contextLayerTypes";

const federalLicence = "https://open.canada.ca/en/open-government-licence-canada";
const geoNovaLicence = "https://nsgi.novascotia.ca/gdd/lic/Unrestricted_Data_Use_Licence.txt";
const geoNovaAttribution = "This product has been produced by or for KinNoKi Labs and includes data provided by the Department of Service Nova Scotia. The incorporation of data sourced from the Department of Service Nova Scotia within this product shall not be construed as constituting an endorsement by the Department of Service Nova Scotia of our product. The province makes no representation or warranty of accuracy, usefulness, novelty, validity, scope, completeness or currency.";
const eccc = "https://maps-cartes.ec.gc.ca/arcgis/rest/services/CWS_SCF/CriticalHabitat/MapServer";
const dfo = "https://egisp.dfo-mpo.gc.ca/arcgis/rest/services/open_data_donnees_ouvertes";
const elc = "https://nsgiwa.novascotia.ca/arcgis/rest/services/FOR/FOR_EcologicalLandClassification_2015_UT83/MapServer";
const ebar = "https://gis.natureserve.ca/arcgis/rest/services/EBAR-KBA/EBARPublic2/MapServer/1";

const fill = (color: string, fillOpacity = 0.24): ContextFeatureStyle => ({
  color, fillColor: color, fillOpacity, weight: 1.5,
});

/** Official habitat designations, published generalized ranges, and broad ecological context. */
export const biodiversityLayers = [
  {
    id: "ns-sar-core-habitat",
    name: "Nova Scotia identified core habitat",
    category: "forestry-ecology",
    serviceUrl: `${import.meta.env.BASE_URL}ecology/ns-core-habitat.geojson`,
    vectorSource: { kind: "geojson", url: `${import.meta.env.BASE_URL}ecology/ns-core-habitat.geojson` },
    sourceUrl: "https://nsgi.novascotia.ca/gdd/",
    licenceUrl: geoNovaLicence,
    licence: "province-unrestricted",
    attribution: geoNovaAttribution,
    sourceDate: "GeoNOVA entry 153, published 2026-01-30; source attributes have per-feature years.",
    scale: "Published provincial polygon boundaries simplified by 20 metres in source UTM coordinates for display.",
    coverage: "Public, identified core-habitat polygons across Nova Scotia; sensitive habitats withheld by the province are absent.",
    webCaveat: "Identified under the Nova Scotia Endangered Species Act, generally not designated by regulation or order. Polygons are not occurrences or proof every location inside meets the recovery document's biophysical conditions. Bat habitat uses generalized 10 × 10 km grid squares. Consult each recovery document. Province makes no warranty of accuracy, completeness or currency.",
    minZoom: 8, maxZoom: 23, opacity: 0.7, zIndex: 216,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID",
    outFields: ["OBJECTID", "CommName", "SciName", "Population", "Taxon", "Year", "Source", "RDoc", "Status", "Ha"],
    labelField: "CommName",
    popupFields: [
      { field: "CommName", label: "Species" }, { field: "SciName", label: "Scientific name" },
      { field: "Population", label: "Population" }, { field: "Status", label: "Habitat status" },
      { field: "Year", label: "Source year" }, { field: "RDoc", label: "Recovery document" },
      { field: "OBJECTID", label: "Source feature ID" },
    ],
    legend: [{ label: "Identified core habitat (not usually legally designated)", color: "#c25079" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#c25079", 0.28) },
  },
  {
    id: "eccc-critical-habitat-area",
    name: "Federal terrestrial critical habitat areas",
    category: "forestry-ecology",
    serviceUrl: `${eccc}/3`,
    sourceUrl: "https://open.canada.ca/data/en/dataset/47caa405-be2b-4e9e-8f53-c478ade2ca74",
    licenceUrl: federalLicence, licence: "canada-open",
    attribution: "Environment and Climate Change Canada, Canadian Wildlife Service; Open Government Licence – Canada.",
    sourceDate: "Federal dataset modified 2026-06-15; recovery-document dates vary by species.",
    scale: "Published terrestrial SARA critical-habitat polygons; grid and polygon resolution varies.",
    coverage: "ECCC and Parks Canada led terrestrial species; mapped coverage is incomplete.",
    webCaveat: "Final critical-habitat mapping, separate from proposed areas and provincial core habitat. Not every place inside a boundary is itself critical habitat; interpret with the species recovery strategy or action plan. Sensitive locations may be generalized or withheld.",
    minZoom: 8, maxZoom: 23, opacity: 0.7, zIndex: 217,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID", outFields: ["OBJECTID", "CommName_E", "SciName", "Population_E", "SARA_Status", "RD_Status", "RDoc_Name_E", "Sensitive_E", "SiteID"],
    labelField: "CommName_E",
    popupFields: [
      { field: "CommName_E", label: "Species" }, { field: "SciName", label: "Scientific name" },
      { field: "Population_E", label: "Population" },
      { field: "SARA_Status", label: "SARA status", values: { "0": "<Null>", "1": "Extirpated", "2": "Endangered", "3": "Threatened", "4": "Special Concern", "5": "No Status", "6": "Not at Risk" } },
      { field: "RD_Status", label: "Recovery document status", values: { "0": "<Null>", "1": "Posted Final", "2": "Posted Proposed", "3": "Not Yet Posted - CH Draft", "4": "Not Yet Posted - CH Candidate", "5": "Archived " } },
      { field: "RDoc_Name_E", label: "Recovery document" },
      { field: "Sensitive_E", label: "Sensitivity" }, { field: "SiteID", label: "Site ID" },
      { field: "OBJECTID", label: "Source feature ID" },
    ],
    legend: [{ label: "Published federal critical-habitat area", color: "#9b435d" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#9b435d", 0.23) },
  },
  {
    id: "eccc-proposed-critical-habitat-area",
    name: "Proposed federal terrestrial critical habitat",
    category: "forestry-ecology",
    serviceUrl: `${eccc}/4`,
    sourceUrl: "https://open.canada.ca/data/en/dataset/47caa405-be2b-4e9e-8f53-c478ade2ca74",
    licenceUrl: federalLicence, licence: "canada-open",
    attribution: "Environment and Climate Change Canada, Canadian Wildlife Service; Open Government Licence – Canada.",
    sourceDate: "Federal dataset modified 2026-06-15; recovery-document dates vary by species.",
    scale: "Published proposed terrestrial SARA critical-habitat polygons; source resolution varies.",
    coverage: "ECCC and Parks Canada led terrestrial species; mapped coverage is incomplete.",
    webCaveat: "Proposed critical habitat is not a final identification or legal designation. Not every place inside a mapped area meets the recovery document's biophysical conditions. An empty view does not show absence of species.",
    minZoom: 8, maxZoom: 23, opacity: 0.65, zIndex: 218,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID", outFields: ["OBJECTID", "CommName_E", "SciName", "Population_E", "SARA_Status", "RD_Status", "RDoc_Name_E", "Sensitive_E", "SiteID"],
    labelField: "CommName_E",
    popupFields: [
      { field: "CommName_E", label: "Species" }, { field: "SciName", label: "Scientific name" },
      { field: "Population_E", label: "Population" },
      { field: "SARA_Status", label: "SARA status", values: { "0": "<Null>", "1": "Extirpated", "2": "Endangered", "3": "Threatened", "4": "Special Concern", "5": "No Status", "6": "Not at Risk" } },
      { field: "RD_Status", label: "Document status", values: { "0": "<Null>", "1": "Posted Final", "2": "Posted Proposed", "3": "Not Yet Posted - CH Draft", "4": "Not Yet Posted - CH Candidate", "5": "Archived " } },
      { field: "RDoc_Name_E", label: "Recovery document" },
      { field: "SiteID", label: "Site ID" },
      { field: "OBJECTID", label: "Source feature ID" },
    ],
    legend: [{ label: "Proposed critical-habitat area", color: "#e08b9a" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#e08b9a", 0.18) },
  },
  {
    id: "dfo-aquatic-critical-habitat",
    name: "DFO aquatic critical habitat",
    category: "forestry-ecology",
    serviceUrl: `${dfo}/dfo_sara_critical_habitat/MapServer/0`,
    sourceUrl: "https://open.canada.ca/data/en/dataset/db177a8c-5d7d-49eb-8290-31e6a45d786c",
    licenceUrl: federalLicence, licence: "canada-open",
    attribution: "Fisheries and Oceans Canada, Species at Risk Program; Open Government Licence – Canada.",
    sourceDate: "Federal dataset updated 2026-05-05; species documents have their own dates.",
    scale: "Published aquatic SARA critical-habitat geometry; mapped watercourses may not align exactly with nature.",
    coverage: "Aquatic species across Canada, including Nova Scotia waters where published.",
    webCaveat: "Aquatic critical habitat is distinct from terrestrial ECCC critical habitat and species distribution. The recovery document governs interpretation. A returned-empty view is not evidence that aquatic habitat or species are absent.",
    minZoom: 8, maxZoom: 23, opacity: 0.7, zIndex: 219,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID", outFields: ["OBJECTID", "COMMON_E", "SCIENTIFIC", "POP_E", "CH_STATUS_E", "SARASTAT_E", "Waterbody", "PROFILE_E"],
    labelField: "COMMON_E",
    popupFields: [
      { field: "COMMON_E", label: "Species" }, { field: "SCIENTIFIC", label: "Scientific name" },
      { field: "POP_E", label: "Population" }, { field: "CH_STATUS_E", label: "Critical-habitat status" },
      { field: "SARASTAT_E", label: "SARA status" }, { field: "Waterbody", label: "Waterbody" },
      { field: "PROFILE_E", label: "Species profile" },
      { field: "OBJECTID", label: "Source feature ID" },
    ],
    legend: [{ label: "DFO aquatic critical habitat", color: "#276e90" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#276e90", 0.26) },
  },
  {
    id: "dfo-aquatic-sar-range",
    name: "DFO aquatic species-at-risk ranges",
    category: "forestry-ecology",
    serviceUrl: `${dfo}/dfo_sara_distribution/MapServer/0`,
    sourceUrl: "https://open.canada.ca/data/en/dataset/e0fabad5-9379-4077-87b9-5705f28c490b",
    licenceUrl: federalLicence, licence: "canada-open",
    attribution: "Fisheries and Oceans Canada, Species at Risk Program; Open Government Licence – Canada.",
    sourceDate: "Federal dataset updated 2026-05-12; source dates vary by species.",
    scale: "Broad species distributions, not observations or critical-habitat boundaries.",
    coverage: "Mapped aquatic species-at-risk ranges across Canada.",
    webCaveat: "A range means a species may occur; it is not a sighting, a survey, or a critical-habitat designation. Empty coverage does not establish absence.",
    minZoom: 7, maxZoom: 23, opacity: 0.55, zIndex: 198,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID", outFields: ["OBJECTID", "COMMON_E", "SCIENTIFIC", "POP_E", "SARASTAT_E", "DATASOURCE", "Waterbody", "PROFILE_E"],
    labelField: "COMMON_E",
    popupFields: [
      { field: "COMMON_E", label: "Species" }, { field: "SCIENTIFIC", label: "Scientific name" },
      { field: "POP_E", label: "Population" }, { field: "SARASTAT_E", label: "SARA status" },
      { field: "DATASOURCE", label: "Range source" }, { field: "Waterbody", label: "Waterbody" },
      { field: "OBJECTID", label: "Source feature ID" },
    ],
    legend: [{ label: "Possible aquatic SAR distribution", color: "#5ca7ba" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#5ca7ba", 0.13) },
  },
  {
    id: "ebar-generalized-species-ranges",
    name: "NatureServe generalized species ranges",
    category: "forestry-ecology",
    serviceUrl: ebar,
    sourceUrl: "https://www.arcgis.com/home/item.html?id=a12d420faa344d5981c1e8f965f4b241",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0/", licence: "cc-by",
    attribution: "EBAR © NatureServe Canada 2020, CC BY 4.0; underlying ecoshape sources are identified in feature metadata.",
    sourceDate: "Live EBAR range service checked 2026-09-27; each feature carries range version/date and review stage.",
    scale: "Generalized ecoshapes; broad distribution context only.",
    coverage: "Nova Scotia ecoshapes from NatureServe Canada terrestrial species ranges.",
    webCaveat: "An ecoshape's presence value does not mean a species is present throughout it. Range maps may contain model or expert opinion and vary in review status. No data does not mean species absence. The NatureServe Network has not endorsed every map.",
    minZoom: 9, maxZoom: 23, opacity: 0.45, zIndex: 195,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "row_number", featureWhere: "jurisdictionabbreviation = 'NS'",
    outFields: ["row_number", "national_engl_name", "national_scientific_name", "presence", "rangestage", "rangedate", "rangeversion", "ecoshapename", "ecoshapesourcename", "ecoshapesourcecitation", "rangemapid"],
    labelField: "national_engl_name",
    popupFields: [
      { field: "national_engl_name", label: "Species" }, { field: "national_scientific_name", label: "Scientific name" },
      { field: "presence", label: "Range presence class" }, { field: "rangestage", label: "Review stage" },
      { field: "rangedate", label: "Range date" }, { field: "rangeversion", label: "Range version" },
      { field: "ecoshapename", label: "Ecoshape" }, { field: "ecoshapesourcename", label: "Ecoshape source" },
      { field: "ecoshapesourcecitation", label: "Ecoshape source citation" },
      { field: "rangemapid", label: "Range map ID" },
    ],
    legend: [{ label: "Generalized range ecoshape; presence varies by feature", color: "#b18d51" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#b18d51", 0.09) },
  },
  {
    id: "dfo-ns-eelgrass-survey-records",
    name: "DFO Nova Scotia eelgrass survey records",
    category: "forestry-ecology",
    serviceUrl: `${dfo}/data_of_eelgrass_zostera_marina_occurrences_in_ns/MapServer/0`,
    sourceUrl: "https://open.canada.ca/data/en/dataset/c32e6a7e-df1d-4d0d-94b5-870430b1a92a",
    licenceUrl: federalLicence, licence: "canada-open",
    attribution: "Fisheries and Oceans Canada, Coastal Ecosystem Science Division; Open Government Licence – Canada.",
    sourceDate: "Federal dataset published 2026-04-09; individual observations span 2009–2024.",
    scale: "Survey locations with source methods and dates; positional precision varies.",
    coverage: "Published Nova Scotia coastal eelgrass sampling locations.",
    webCaveat: "Presence and absence are observations only at the sampled location and time. Methods and data owners vary. A zero record or empty map is not evidence of eelgrass absence elsewhere along the coast.",
    minZoom: 11, maxZoom: 23, opacity: 0.8, zIndex: 222,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID",
    outFields: ["OBJECTID", "site", "subsite_sous_site", "year_année", "month_mois", "day_jour", "eelgrass_PA_zostère_marine_PA", "sampling_type_typ__d_échantillonnage", "data_owner_propriétaire_des_données", "data_source_reference1_source_des_données_référence1"],
    labelField: "site",
    popupFields: [
      { field: "site", label: "Site" }, { field: "subsite_sous_site", label: "Subsite" },
      { field: "eelgrass_PA_zostère_marine_PA", label: "Eelgrass present (1) / absent (0)" },
      { field: "year_année", label: "Observation year" }, { field: "month_mois", label: "Month" },
      { field: "day_jour", label: "Day" },
      { field: "sampling_type_typ__d_échantillonnage", label: "Sampling method" },
      { field: "data_owner_propriétaire_des_données", label: "Data owner" },
      { field: "OBJECTID", label: "Source record ID" },
    ],
    legend: [
      { label: "Observed eelgrass presence (1)", color: "#2b8063" },
      { label: "Observed eelgrass absence (0)", color: "#9b7850" },
    ],
    featureRenderer: {
      field: "eelgrass_PA_zostère_marine_PA",
      styles: {
        "1": { ...fill("#2b8063", 0.55), radius: 5 },
        "0": { ...fill("#9b7850", 0.55), radius: 5 },
      },
      defaultStyle: { ...fill("#666666", 0.45), radius: 5 },
    },
  },
  {
    id: "canadian-national-wetlands-inventory",
    printLegend: true,
    name: "Canadian National Wetlands Inventory",
    category: "forestry-ecology",
    serviceUrl: "https://maps-cartes.ec.gc.ca/arcgis/rest/services/CWS_SCF/CNWI/MapServer",
    sourceUrl: "https://open.canada.ca/data/en/dataset/d5af4ac5-ebdb-4645-bb0a-8ec5cac5e29f",
    licenceUrl: federalLicence, licence: "canada-open",
    attribution: "Environment and Climate Change Canada, Canadian Wildlife Service; Open Government Licence – Canada. The inventory harmonizes underlying provincial and other source datasets.",
    sourceDate: "National inventory as of May 2025; federal catalog updated 2025-10-15. Underlying source dates vary.",
    scale: "Publisher's classified wetland image appears at 1:100,000 or closer; no feature-level query is available from this service.",
    coverage: "Published inventory coverage in ten provinces and territories, including mapped parts of Nova Scotia.",
    webCaveat: "Harmonized source wetland mapping, not an independent confirmation of the provincial inventory or a field delineation. Some wetlands are unmapped; a blank view at this scale or outside source coverage does not establish absence. Source feature identity is unavailable from this image service.",
    minZoom: 13, maxZoom: 23, maxNativeZoom: 18, opacity: 0.82, zIndex: 207,
    exportOptions: { transparent: true, layers: "show:1" },
    legend: [
      { label: "Bog", color: "#8a4f0b" },
      { label: "Peatland", color: "#bd7f2d" },
      { label: "Fen; Rich Fen; Poor Fen", color: "#dec17e" },
      { label: "Unclassified", color: "#f5e7c4" },
      { label: "Open Water; Shallow Water; Shallow or Open Water", color: "#c8e8e3" },
      { label: "Mixed", color: "#81ccbf" },
      { label: "Marsh; Organic Marsh; Mineral Marsh", color: "#36968e" },
      { label: "Swamp; Organic Swamp; Mineral Swamp", color: "#01665e" },
    ],
  },
  {
    id: "ns-ecological-districts-2015",
    name: "Nova Scotia ecological districts (2015)",
    category: "forestry-ecology",
    serviceUrl: `${elc}/1`, sourceUrl: "https://nsgi.novascotia.ca/gdd/",
    licenceUrl: geoNovaLicence, licence: "province-unrestricted", attribution: geoNovaAttribution,
    sourceDate: "ELC 2015 classification; GeoNOVA entry 105 published 2018-11-08.",
    scale: "Regional ecological district boundaries; landscape context.",
    coverage: "Nova Scotia ecological land classification.",
    webCaveat: "An ecological district describes broad landscape patterns, not species presence, a field-verified habitat or a site condition. Province makes no warranty of accuracy, completeness or currency.",
    minZoom: 7, maxZoom: 23, opacity: 0.55, zIndex: 185,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID", outFields: ["OBJECTID", "ECODISTRIC", "ECOREGION", "ELARPTNAME", "HECTARES"],
    labelField: "ELARPTNAME",
    popupFields: [
      { field: "ELARPTNAME", label: "District name" }, { field: "ECODISTRIC", label: "District code" },
      { field: "ECOREGION", label: "Ecoregion" },
    ],
    legend: [{ label: "Ecological district", color: "#598e69" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#598e69", 0.07) },
  },
  {
    id: "ns-ecological-sections-2015",
    name: "Nova Scotia ecological sections (2015)",
    category: "forestry-ecology",
    serviceUrl: `${elc}/2`, sourceUrl: "https://nsgi.novascotia.ca/gdd/",
    licenceUrl: geoNovaLicence, licence: "province-unrestricted", attribution: geoNovaAttribution,
    sourceDate: "ELC 2015 classification; GeoNOVA entry 105 published 2018-11-08.",
    scale: "Ecological sections interpreted from landscape attributes; boundaries are contextual.",
    coverage: "Nova Scotia ecological land classification.",
    webCaveat: "Ecological sections are classified landscape context, not a survey of conditions on a property or evidence of species presence. Province makes no warranty of accuracy, completeness or currency.",
    minZoom: 10, maxZoom: 23, opacity: 0.5, zIndex: 186,
    exportOptions: { transparent: true }, delivery: "feature-query",
    idField: "OBJECTID", outFields: ["OBJECTID", "ELC_ID", "ECOREGION", "ECODISTRIC", "ECOSECTION", "NDR", "DRAINAGE", "TEXTURE", "TOPOGRAPHY"],
    labelField: "ECOSECTION",
    popupFields: [
      { field: "ECOSECTION", label: "Ecosection" }, { field: "ELC_ID", label: "ELC ID" },
      { field: "ECODISTRIC", label: "District" }, { field: "NDR", label: "Natural disturbance regime" },
      { field: "DRAINAGE", label: "Drainage class" }, { field: "TEXTURE", label: "Texture" },
    ],
    legend: [{ label: "Ecological section", color: "#6c9f72" }],
    featureRenderer: { styles: {}, defaultStyle: fill("#6c9f72", 0.07) },
  },
] as const satisfies readonly ContextLayerDescriptor[];
