import type { ContextLayerDescriptor } from "./contextLayerTypes";

// Publisher schemas, licence metadata, and local coverage checked 27 September 2026.
// These are source records and mapped locations, not site inspections or impact findings.
export const communityResearchLayers = [
  {
    id: "traffic-survey-sections",
    name: "Traffic survey sections (2024)",
    category: "roads-places",
    serviceUrl: "https://data.novascotia.ca/resource/vg5n-eehf.geojson",
    sourceUrl: "https://data.novascotia.ca/d/vg5n-eehf",
    licenceUrl: "https://novascotia.ca/opendata/licence.asp",
    licence: "province-open",
    attribution: "Source: Nova Scotia Public Works, Traffic Volume Sections; Open Government Licence – Nova Scotia.",
    sourceDate: "2024 traffic survey section geometry; rows updated 20 April 2026; schema and licence checked 27 September 2026.",
    scale: "Published survey section lines, not measured traffic volumes or route capacity.",
    coverage: "Nova Scotia provincial highway sections represented in the 2024 traffic volume geometry dataset.",
    webCaveat: "Lines identify traffic survey sections only. Counts, truck share and survey dates are in a separate table and are not joined here; a line alone cannot establish current traffic or project transport effects.",
    minZoom: 11,
    maxZoom: 23,
    opacity: 0.8,
    zIndex: 233,
    exportOptions: { transparent: true },
    openData: {
      parts: [{ dataset: "vg5n-eehf", fields: ["section_id", "sect_desc", "county"] }],
      color: "#b07939",
      fillOpacity: 0,
      stroke: true,
      labelField: "section_id",
      labelMinZoom: 14,
    },
    legend: [{ label: "2024 traffic survey section", color: "#b07939" }],
  },
  {
    id: "public-works-structures",
    name: "Public Works bridges and culverts",
    category: "roads-places",
    serviceUrl: "https://data.novascotia.ca/resource/gs26-c3fm.json",
    sourceUrl: "https://data.novascotia.ca/d/gs26-c3fm",
    licenceUrl: "https://novascotia.ca/opendata/licence.asp",
    licence: "province-open",
    attribution: "Source: Nova Scotia Public Works, Structures Database; Open Government Licence – Nova Scotia.",
    sourceDate: "Source rows updated 20 April 2026; schema and licence checked 27 September 2026.",
    scale: "Published structure coordinates; locations are not surveyed crossing limits.",
    coverage: "Public Works owned or maintained bridges, culverts at least 3 m long, and overhead signs across Nova Scotia.",
    webCaveat: "An inventory point does not establish load capacity, condition, fish passage or coverage of smaller and private culverts.",
    minZoom: 11,
    maxZoom: 23,
    opacity: 0.85,
    zIndex: 235,
    exportOptions: { transparent: true },
    delivery: "feature-query",
    vectorSource: {
      kind: "socrata-points",
      dataset: "gs26-c3fm",
      latitudeField: "latitude",
      longitudeField: "longitude",
      fields: ["structureid", "structurename"],
    },
    idField: "source_row_id",
    outFields: ["source_row_id", "structureid", "structurename"],
    labelField: "structurename",
    popupFields: [{ field: "structureid", label: "Structure ID" }],
    featureRenderer: {
      styles: {},
      defaultStyle: { color: "#8558a4", fillColor: "#8558a4", fillOpacity: 0.8, weight: 1, radius: 5 },
    },
    legend: [{ label: "Public Works structure", color: "#8558a4" }],
  },
  {
    id: "tourism-listed-operators",
    name: "Listed tourism operators",
    category: "roads-places",
    serviceUrl: "https://data.novascotia.ca/resource/2h2s-6bg4.json",
    sourceUrl: "https://data.novascotia.ca/d/2h2s-6bg4",
    licenceUrl: "https://novascotia.ca/opendata/licence.asp",
    licence: "province-open",
    attribution: "Source: Tourism Nova Scotia, listed operators; Open Government Licence – Nova Scotia.",
    sourceDate: "Source rows updated 6 June 2025; schema and licence checked 27 September 2026.",
    scale: "Listed operator coordinates; points do not map full trails, properties or visitor areas.",
    coverage: "Tourism Nova Scotia listed operators across Nova Scotia; listings and positions can change.",
    webCaveat: "One destination may have multiple listings by business category. A listed trail point is not its route or a grant of access, and a listing does not establish visitor numbers or project effects.",
    minZoom: 11,
    maxZoom: 23,
    opacity: 0.85,
    zIndex: 236,
    exportOptions: { transparent: true },
    delivery: "feature-query",
    vectorSource: {
      kind: "socrata-points",
      dataset: "2h2s-6bg4",
      latitudeField: "latitude",
      longitudeField: "longitude",
      fields: ["name", "type", "region"],
    },
    idField: "source_row_id",
    outFields: ["source_row_id", "name", "type", "region"],
    labelField: "name",
    popupFields: [{ field: "type", label: "Listing type" }, { field: "region", label: "Tourism region" }],
    featureRenderer: {
      styles: {},
      defaultStyle: { color: "#be6a34", fillColor: "#be6a34", fillOpacity: 0.8, weight: 1, radius: 5 },
    },
    legend: [{ label: "Listed operator", color: "#be6a34" }],
  },
  {
    id: "registered-heritage-properties",
    name: "Registered heritage properties",
    category: "roads-places",
    serviceUrl: "https://data.novascotia.ca/resource/7pnv-7sdm.json",
    sourceUrl: "https://data.novascotia.ca/d/7pnv-7sdm",
    licenceUrl: "https://novascotia.ca/opendata/licence.asp",
    licence: "province-open",
    attribution: "Source: Nova Scotia Heritage Property Program, Registered Heritage Properties; Open Government Licence – Nova Scotia.",
    sourceDate: "Source rows updated 17 July 2026; schema and licence checked 27 September 2026.",
    scale: "Published heritage record coordinates; markers do not delineate a designated property.",
    coverage: "Published registered heritage properties across Nova Scotia; unlisted places may still have heritage value.",
    webCaveat: "Registration is tied to the source record. A point does not establish a parcel match, owner, impact or access right.",
    minZoom: 11,
    maxZoom: 23,
    opacity: 0.85,
    zIndex: 237,
    exportOptions: { transparent: true },
    delivery: "feature-query",
    vectorSource: {
      kind: "socrata-points",
      dataset: "7pnv-7sdm",
      latitudeField: "latitude",
      longitudeField: "longitude",
      fields: ["unique_identifier_file_no", "property_name", "type", "community", "level_of_registration", "notice_of_registration_date"],
    },
    idField: "source_row_id",
    outFields: ["source_row_id", "unique_identifier_file_no", "property_name", "type", "community", "level_of_registration", "notice_of_registration_date"],
    labelField: "property_name",
    popupFields: [
      { field: "unique_identifier_file_no", label: "Heritage record" },
      { field: "type", label: "Property type" },
      { field: "community", label: "Community" },
      { field: "level_of_registration", label: "Registration level" },
      { field: "notice_of_registration_date", label: "Registration notice date" },
    ],
    featureRenderer: {
      styles: {},
      defaultStyle: { color: "#8d4f69", fillColor: "#8d4f69", fillOpacity: 0.8, weight: 1, radius: 5 },
    },
    legend: [{ label: "Registered heritage record", color: "#8d4f69" }],
  },
  {
    id: "npri-reporting-facilities-2024",
    name: "NPRI reporting facilities (2024)",
    category: "roads-places",
    serviceUrl: "https://maps-cartes.ec.gc.ca/arcgis/rest/services/STB_DGST/NPRI/MapServer/0",
    sourceUrl: "https://open.canada.ca/data/en/dataset/3b7dd693-52dc-4e55-828f-37c8172f009b",
    licenceUrl: "https://open.canada.ca/en/open-government-licence-canada",
    licence: "canada-open",
    attribution: "Source: Environment and Climate Change Canada, National Pollutant Release Inventory 2024 reporting facilities; Open Government Licence – Canada.",
    sourceDate: "2024 reporting year; service schema and licence checked 27 September 2026.",
    scale: "Reported facility locations; a marker is not an emission footprint or monitoring location.",
    coverage: "Facilities across Canada that reported to NPRI for 2024; reporting thresholds and exemptions limit coverage.",
    webCaveat: "A facility point does not show pollutant quantities, ambient concentrations, exposure or effects on nearby land. No reported facility in a view does not establish absence of industrial activity.",
    minZoom: 9,
    maxZoom: 23,
    opacity: 0.85,
    zIndex: 239,
    exportOptions: { transparent: true },
    delivery: "feature-query",
    idField: "OBJECTID_1",
    outFields: ["OBJECTID_1", "NpriID", "FacilityName", "CompanyName", "ReportYear", "SectorDescriptionEn"],
    labelField: "FacilityName",
    popupFields: [
      { field: "NpriID", label: "NPRI facility ID" },
      { field: "CompanyName", label: "Reporting company" },
      { field: "ReportYear", label: "Reporting year" },
      { field: "SectorDescriptionEn", label: "Sector" },
    ],
    featureRenderer: {
      styles: {},
      defaultStyle: { color: "#846645", fillColor: "#846645", fillOpacity: 0.85, weight: 1, radius: 5 },
    },
    legend: [{ label: "2024 reporting facility", color: "#846645" }],
  },
  {
    id: "canadian-wind-turbines",
    name: "Installed wind turbines (NRCan)",
    category: "roads-places",
    serviceUrl: "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/wind_turbine_database2_en/MapServer/6",
    sourceUrl: "https://open.canada.ca/data/en/dataset/79fdad93-9025-49ad-ba16-c26d718cc070",
    licenceUrl: "https://open.canada.ca/en/open-government-licence-canada",
    licence: "canada-open",
    attribution: "Source: Natural Resources Canada, Canadian Wind Turbine Database; Open Government Licence – Canada.",
    sourceDate: "Database temporal coverage through 16 September 2025; catalogue updated April 2026; service checked 27 September 2026.",
    scale: "Published turbine point locations; coordinates and equipment attributes are database records.",
    coverage: "Canadian installed wind turbines reported in the NRCan database; inventory may lag additions and retirements.",
    webCaveat: "These are inventoried turbines, not proposals or a current field inspection. Hub height, rotor diameter, capacity and commissioning year are source attributes, not measurements made for this map.",
    minZoom: 9,
    maxZoom: 23,
    opacity: 0.85,
    zIndex: 238,
    exportOptions: { transparent: true, layers: "show:6" },
    delivery: "feature-query",
    idField: "OBJECTID",
    outFields: ["OBJECTID", "Project_Name", "Turbine_Identifier", "Turbine_Rated_Capacity_kW", "Hub_Height_m", "Rotor_Diameter_m", "Commissioning"],
    labelField: "Turbine_Identifier",
    popupFields: [
      { field: "Project_Name", label: "Project" },
      { field: "Turbine_Rated_Capacity_kW", label: "Rated capacity (kW)" },
      { field: "Hub_Height_m", label: "Hub height (m)" },
      { field: "Rotor_Diameter_m", label: "Rotor diameter (m)" },
      { field: "Commissioning", label: "Commissioning year" },
    ],
    featureRenderer: {
      styles: {},
      defaultStyle: { color: "#417b91", fillColor: "#417b91", fillOpacity: 0.85, weight: 1, radius: 6 },
    },
    legend: [{ label: "Inventoried installed turbine", color: "#417b91" }],
  },
] as const satisfies readonly ContextLayerDescriptor[];
