import type { ContextLayerDescriptor } from "./contextLayerTypes";
import subTertiaryCoverage from "../data/subTertiaryCoverage.json";

const NS_OPEN_LICENCE = "https://novascotia.ca/opendata/licence.asp";
const CA_OPEN_LICENCE = "https://open.canada.ca/en/open-government-licence-canada";
const NSHN = "https://nsgiwa.novascotia.ca/arcgis/rest/services/WTR/WTR_NSHN_UT83/MapServer";
const DFO_COAST = "https://egisp.dfo-mpo.gc.ca/arcgis/rest/services/open_data_donnees_ouvertes/land_use_atlas_coastal_watersheds_maritimes_region/MapServer";

/** Publisher-authored research context; each layer retains its own lineage and limits. */
export const waterResearchLayers = [
  {
    id: "nshn-spines",
    name: "NSHN connected water spines",
    category: "water-terrain",
    delivery: "feature-query",
    serviceUrl: `${NSHN}/9`,
    sourceUrl: "https://data.novascotia.ca/d/dk27-q8k2",
    licenceUrl: NS_OPEN_LICENCE,
    licence: "province-open",
    attribution: "Contains information licensed under the Open Government Licence – Nova Scotia. Source: Nova Scotia Hydrographic Network, Province of Nova Scotia.",
    sourceDate: "NSHN catalogue records last updated 2020; live service checked 27 September 2026. Segment capture dates vary.",
    scale: "NSTDB-derived connected network; mapped alignment is not a field survey",
    coverage: "Nova Scotia inland surface-water network; unmapped or intermittent channels may exist",
    webCaveat: "Connected centreline spines supplement mapped rivers. Published flow-direction and priority codes are shown without interpretation; this is not a traced drainage path, fish passage assessment or crossing inventory.",
    minZoom: 12,
    maxZoom: 23,
    opacity: 0.85,
    zIndex: 209,
    exportOptions: { transparent: true, layers: "show:9" },
    idField: "OBJECTID",
    outFields: ["OBJECTID", "HID", "RIVNAME_1", "FEAT_DESC", "FLOWDIR", "LEVELPRIOR"],
    labelField: "RIVNAME_1",
    popupFields: [
      { field: "RIVNAME_1", label: "Published name" },
      { field: "FEAT_DESC", label: "Spine class" },
      { field: "FLOWDIR", label: "Flow direction code" },
      { field: "LEVELPRIOR", label: "Flow priority code" },
      { field: "HID", label: "NSHN segment ID" },
    ],
    featureRenderer: { defaultStyle: { color: "#0c7f9b", weight: 2.2, fillOpacity: 0 }, styles: {} },
    legend: [{ label: "Mapped connected water spine", color: "#0c7f9b" }],
  },
  {
    id: "sub-tertiary-watersheds",
    name: "Sub-tertiary watershed units",
    category: "water-terrain",
    serviceUrl: "https://data.novascotia.ca/resource/s4r5-2srh.geojson",
    sourceUrl: "https://data.novascotia.ca/d/s4r5-2srh",
    licenceUrl: NS_OPEN_LICENCE,
    licence: "province-open",
    attribution: "Contains information licensed under the Open Government Licence – Nova Scotia. Source: 1:10,000 Nova Scotia Sub-Tertiary Watersheds.",
    sourceDate: "Mapped watershed data last updated 2021; open dataset checked 27 September 2026",
    scale: "1:10,000 mapped drainage units; not parcel-scale catchments",
    coverage: "Selected Tusket, St. Croix, Shubenacadie, LaHave, St. Mary's and Margaree River basins only; no mapped Rhodena coverage",
    webCaveat: "These finer units exist for six named basins only. A blank area elsewhere means outside this layer's coverage, not that no watershed exists. The map's existing watershed layer has province-wide primary through tertiary units.",
    minZoom: 10,
    maxZoom: 23,
    opacity: 0.7,
    zIndex: 183,
    exportOptions: { transparent: true },
    openData: { parts: [{ dataset: "s4r5-2srh", fields: ["sub_tert_c", "sub_tertia", "tert_code", "sec_code", "sec_name"] }], color: "#7e55a1", fillOpacity: 0.04, coverageAreas: subTertiaryCoverage.areas },
    legend: [{ label: "Mapped sub-tertiary unit in six covered basins", color: "#7e55a1" }],
  },
  {
    id: "dfo-coastal-watersheds",
    name: "DFO coastal watershed units",
    category: "water-terrain",
    delivery: "feature-query",
    serviceUrl: `${DFO_COAST}/4`,
    sourceUrl: "https://open.canada.ca/data/en/dataset/85d6c4c2-6683-4d56-adf4-8cacef2676be",
    licenceUrl: CA_OPEN_LICENCE,
    licence: "canada-open",
    attribution: "Contains information licensed under the Open Government Licence – Canada. Source: Fisheries and Oceans Canada, Land Use Atlas for Coastal Watersheds in the Maritimes Region.",
    sourceDate: "DFO coastal land-use atlas published 2022; source inputs span 1986–2020; service checked 27 September 2026",
    scale: "Regional receiving-watershed summaries; not parcel-scale land use or current conditions",
    coverage: "DFO Maritimes coastal-watershed study areas; two units intersect the Rhodena study window",
    webCaveat: "Watershed boundaries support regional receiving-water context. The published area and ID do not identify a parcel's drainage route or current land condition.",
    minZoom: 10,
    maxZoom: 23,
    opacity: 0.8,
    zIndex: 184,
    exportOptions: { transparent: true, layers: "show:4" },
    idField: "OBJECTID",
    outFields: ["OBJECTID", "Watershed_ID", "Area_ha", "Province", "Biogeographic_Region"],
    labelField: "Watershed_ID",
    popupFields: [
      { field: "Watershed_ID", label: "DFO watershed ID" },
      { field: "Area_ha", label: "Published watershed area (ha)" },
      { field: "Biogeographic_Region", label: "Biogeographic region" },
    ],
    featureRenderer: { defaultStyle: { color: "#a4a000", fillColor: "#a4a000", fillOpacity: 0.025, weight: 1.7 }, styles: {} },
    legend: [{ label: "DFO coastal watershed boundary", color: "#a4a000" }],
  },
  {
    id: "dfo-coastal-land-use",
    printLegend: true,
    name: "DFO coastal watershed land use",
    category: "water-terrain",
    serviceUrl: DFO_COAST,
    sourceUrl: "https://open.canada.ca/data/en/dataset/85d6c4c2-6683-4d56-adf4-8cacef2676be",
    licenceUrl: CA_OPEN_LICENCE,
    licence: "canada-open",
    attribution: "Contains information licensed under the Open Government Licence – Canada. Source: Fisheries and Oceans Canada, Land Use Atlas for Coastal Watersheds in the Maritimes Region.",
    sourceDate: "DFO atlas published 2022; source inputs span 1986–2020; service checked 27 September 2026",
    scale: "Atlas land-use classes compiled across coastal watersheds; vintages vary",
    coverage: "DFO Maritimes coastal-watershed study areas; classified polygons intersect the Rhodena study window",
    webCaveat: "Atlas classes combine sources from 1986–2020 and describe regional land use, not current clearing or a site survey. Wetland here is an atlas class, not a field-delineated wetland.",
    minZoom: 10,
    maxZoom: 23,
    opacity: 0.43,
    zIndex: 169,
    exportOptions: { transparent: true, layers: "show:3" },
    legend: [
      { label: "Agriculture", color: "#ffaa00" },
      { label: "Forest", color: "#d3febd" },
      { label: "Impervious surface", color: "#e600a9" },
      { label: "Peatland", color: "#734c00" },
      { label: "Pervious surface", color: "#fe73df" },
      { label: "Water features", color: "#bee8ff" },
      { label: "Wetland", color: "#00a884" },
    ],
  },
  {
    id: "wsc-hydrometric-stations",
    name: "Water Survey of Canada stations",
    category: "water-terrain",
    delivery: "feature-query",
    serviceUrl: "https://api.weather.gc.ca/collections/hydrometric-stations/items",
    vectorSource: { kind: "ogc-features" },
    sourceUrl: "https://open.canada.ca/data/en/dataset/46763060-e859-4812-8da5-2361d99b4c34",
    licenceUrl: CA_OPEN_LICENCE,
    licence: "canada-open",
    attribution: "Contains information licensed under the Open Government Licence – Canada. Source: Water Survey of Canada hydrometric station inventory, Environment and Climate Change Canada.",
    sourceDate: "Live hydrometric station inventory checked 27 September 2026; individual station activity periods vary",
    scale: "Published station point; drainage area and observed readings are station-specific",
    coverage: "Canadian station network; one inventory point intersects the Rhodena study window",
    webCaveat: "A nearby gauge describes conditions at its own site. Basin connection, upstream area and comparable flow at the project are unverified; point presence is not a project hydrology baseline.",
    minZoom: 8,
    maxZoom: 23,
    opacity: 0.95,
    zIndex: 220,
    exportOptions: { transparent: true },
    idField: "IDENTIFIER",
    outFields: ["IDENTIFIER", "STATION_NAME", "STATUS_EN", "REAL_TIME", "DRAINAGE_AREA_GROSS", "VERTICAL_DATUM", "PROV_TERR_STATE_LOC"],
    labelField: "STATION_NAME",
    popupFields: [
      { field: "IDENTIFIER", label: "Station number" },
      { field: "STATION_NAME", label: "Station name" },
      { field: "STATUS_EN", label: "Inventory status" },
      { field: "DRAINAGE_AREA_GROSS", label: "Published gross drainage area (km²)" },
      { field: "VERTICAL_DATUM", label: "Vertical datum" },
    ],
    featureRenderer: { defaultStyle: { color: "#1768a3", fillColor: "#1768a3", fillOpacity: 0.9, radius: 6 }, styles: {} },
    legend: [{ label: "Published hydrometric station", color: "#1768a3" }],
  },
] as const satisfies readonly ContextLayerDescriptor[];
