"""Geographic panels embedded in A.F. Church county sheets.

Some Church sheets are composites: the county is split into multiple map
panels and surrounded by title art or town-plan insets. A panel owns an
explicit non-rectangular `cutline`, while GCP CSVs continue to use coordinates
from the complete archival scan.

Every coordinate below was measured, not estimated. `tools/church/detect_rules.py`
block-minimum reduces the scan, thresholds the heavy engraved rules, and runs a
probabilistic Hough transform; the resulting segments give the neat lines, the
panel divider, and every inset box to within a few pixels. The derivation and
the exact segment evidence are recorded in
`docs/church-inverness-cutlines-2026-07-24.md`.
"""

from __future__ import annotations

from dataclasses import dataclass

from tools.church.cutlines import Cutline
from tools.church.graticule import GraticuleAnchor
from tools.church.windows import SourceWindow

__all__ = [
    "ChurchPanel",
    "DetectionSettings",
    "GeographicBounds",
    "GraticuleSettings",
    "SourceWindow",
    "get_panel",
    "panels_for_county",
]


@dataclass(frozen=True)
class DetectionSettings:
    """How to find one panel's graticule linework in the scan.

    Versioned rather than typed on a command line. These are not preferences:
    re-running the Inverness north detection at the tool's default minimum
    length of 600 reduced pixels instead of the 500 actually used finds only
    four of the six parallels, and silently emits a 20-point mesh instead of a
    30-point one. A parameter that changes how many control points exist
    belongs in version control.
    """

    factor: int
    darkness: int
    min_length_px: int
    angles_deg: tuple[float, float] | None
    """Pinned family angles, measured from a printed label. None means fall back
    to the orientation histogram, which dense coastal hachure can win."""


@dataclass(frozen=True)
class GraticuleSettings:
    """How to turn a panel's detected linework into named control points.

    The anchor is the reading of a printed degree/minute label off the archival
    scan. Committing it is what lets the control CSV be regenerated byte-for-
    byte instead of depending on whatever someone typed the first time - the
    first emission of the Inverness north CSV typed the anchor latitude as
    `46.833333` rather than exactly 46 degrees 50 minutes, and every coordinate
    in the file inherited that rounding.
    """

    anchor: GraticuleAnchor
    tolerance_px: float
    min_extent_px: float
    anchor_evidence: str


@dataclass(frozen=True)
class GeographicBounds:
    """A target longitude/latitude extent in west, south, east, north order."""

    west: float
    south: float
    east: float
    north: float


@dataclass(frozen=True)
class ChurchPanel:
    """One independently georeferenced geographic panel on a county sheet."""

    county_slug: str
    slug: str
    cutline: Cutline
    target_bounds: GeographicBounds
    target_resolution_m: float
    detection: DetectionSettings | None = None
    graticule: GraticuleSettings | None = None
    """None until a panel's printed graticule has actually been read off the scan.

    Deliberately not defaulted to the neighbouring panel's settings: the two
    Inverness panels are drawn on different projection centres, so their
    meridians and parallels meet the sheet at different angles.
    """

    @property
    def window(self) -> SourceWindow:
        """Smallest whole-pixel crop feeding gdal_translate -srcwin.

        Derived, never stored: a window that could drift out of step with its
        cutline is the 2026-07-24 failure waiting to happen again.
        """
        return self.cutline.bounding_window


# The 1884 Inverness sheet is split by a two-segment engraved divider, not the
# single straight edge a first reading suggests. Fitted from the Hough segments:
#
#   upper  x(y) = 15852 - 0.175874 * (y -   732)   for   732 <= y <= 23928
#   lower  x(y) = 11776 - 0.466540 * (y - 23924)   for 23928 <= y <= 29550
#
# meeting at the bend (11773, 23928). Each panel's cutline is offset 60 px to
# its own side of that centreline so the ~30 px engraved rule itself is warped
# into neither panel.
_DIVIDER_NORTH_HEAD = (15784.0, 780.0)
_DIVIDER_NORTH_BEND = (11713.0, 23928.0)
_DIVIDER_NORTH_FOOT = (9283.0, 29140.0)

_DIVIDER_SOUTH_HEAD = (15904.0, 780.0)
_DIVIDER_SOUTH_BEND = (11833.0, 23928.0)
_DIVIDER_SOUTH_FOOT = (9225.0, 29520.0)

_INVERNESS_NORTH_CUTLINE = Cutline(
    (
        # East along the top neat line from the title block to the divider.
        (8850.0, 780.0),
        _DIVIDER_NORTH_HEAD,
        # Down the divider, through its bend, to the panel's own bottom rule.
        _DIVIDER_NORTH_BEND,
        _DIVIDER_NORTH_FOOT,
        # West along the "NORTHERN SECTION" bottom rule (detected at y~29160).
        (1050.0, 29140.0),
        # North up the west neat line, then step around the title cartouche,
        # compass rose, and imprint - all of which sit over open Gulf water, so
        # excluding them costs no map content.
        (1050.0, 9200.0),
        (8850.0, 9200.0),
    )
)

_INVERNESS_SOUTH_CUTLINE = Cutline(
    (
        _DIVIDER_SOUTH_HEAD,
        # Notch around the engraved building vignette, which sits offshore in
        # Northumberland Strait.
        (17050.0, 780.0),
        (17050.0, 3550.0),
        (20100.0, 3550.0),
        (20100.0, 780.0),
        # East neat line, stepping around the West Bay inset.
        (33500.0, 780.0),
        (33500.0, 9850.0),
        (30380.0, 9850.0),
        (30380.0, 14120.0),
        (33500.0, 14120.0),
        # ... and around the Port Hood inset, which reaches the bottom rule.
        (33500.0, 28100.0),
        (30120.0, 28100.0),
        (30120.0, 30330.0),
        # West along the top of the bottom inset row: Port Hastings, Margaree,
        # then down into the Strait of Canso gap, then Mabou and Whycocomagh.
        (25580.0, 30330.0),
        (25580.0, 30900.0),
        (22620.0, 30900.0),
        (22620.0, 33750.0),
        (16920.0, 33750.0),
        (16920.0, 30440.0),
        (12680.0, 30440.0),
        (12680.0, 29520.0),
        _DIVIDER_SOUTH_FOOT,
        _DIVIDER_SOUTH_BEND,
    )
)

# Two degree/minute labels were read directly off the scan. 60d40'W x 47d00'N
# sits at ~(12388, 3188), where the fitted meridian at index 0 passes through
# x = 12,389 - a one-pixel agreement. 60d50'W was then PREDICTED at x = 9,521
# before its crop was taken, and measured at 9,526. Two labels ten arcminutes
# and two lattice steps apart fix the step at 5 arcminutes and rule out the 10'
# alternative; independently, a 10' step would put the westernmost meridian
# offshore at 61d20'W, whereas it falls inland of the coast.
_INVERNESS_NORTH_GRATICULE = GraticuleSettings(
    anchor=GraticuleAnchor(
        meridian_index=0,
        meridian_lon=-(60.0 + 40.0 / 60.0),
        parallel_index=0,
        parallel_lat=46.0 + 50.0 / 60.0,
        step_minutes=5.0,
    ),
    tolerance_px=120.0,
    min_extent_px=3500.0,
    anchor_evidence=(
        "engraved labels 60d40'W x 47d00'N at ~(12388,3188) and 60d50'W at "
        "~(9526,28276) on RUMSEY~8~1~353591~90120835"
    ),
)

_INVERNESS_NORTH_DETECTION = DetectionSettings(
    factor=4,
    darkness=140,
    min_length_px=500,
    angles_deg=(84.5, 174.5),
)

_PANELS = {
    ("inverness", "north"): ChurchPanel(
        county_slug="inverness",
        slug="north",
        cutline=_INVERNESS_NORTH_CUTLINE,
        target_bounds=GeographicBounds(west=-61.35, south=46.30, east=-60.45, north=47.10),
        target_resolution_m=5.0,
        detection=_INVERNESS_NORTH_DETECTION,
        graticule=_INVERNESS_NORTH_GRATICULE,
    ),
    ("inverness", "south"): ChurchPanel(
        county_slug="inverness",
        slug="south",
        cutline=_INVERNESS_SOUTH_CUTLINE,
        target_bounds=GeographicBounds(west=-61.70, south=45.55, east=-60.55, north=46.40),
        target_resolution_m=5.0,
    ),
}


def get_panel(county_slug: str, panel_slug: str) -> ChurchPanel:
    """Return one registered panel."""
    try:
        return _PANELS[(county_slug, panel_slug)]
    except KeyError:
        raise KeyError(f"unknown Church panel: {county_slug}/{panel_slug}") from None


def panels_for_county(county_slug: str) -> list[ChurchPanel]:
    """Return a county's panels in display order."""
    return [
        panel
        for (registered_county, _), panel in _PANELS.items()
        if registered_county == county_slug
    ]
