"""Preserve failed thirteen-control stage and supply supported McKenzie junction."""
from pathlib import Path
import json,hashlib,datetime,copy
D=Path(__file__).resolve().parent
if (D/'final-freeze.json').exists():raise SystemExit('Frozen evidence exists; use a new directory.')
r=lambda n:json.loads((D/n).read_text());h=lambda n:hashlib.sha256((D/n).read_bytes()).hexdigest();w=lambda n,v:(D/n).write_text(json.dumps(v,indent=2)+'\n')
f=r('repaired-fit.json');v=r('validation.json');p=copy.deepcopy(next(p for p in v['points'] if p['id']=='F02'));p.update(id='C15',role='control',status='Promoted unchanged after thirteen-control failure; permanently diagnostic.',promotion={'old_point':next(p for p in v['points'] if p['id']=='F02'),'old_result':next(p for p in r('validation-scores.json')['points'] if p['id']=='F02'),'baseline_result':next(p for p in r('baseline-validation-scores.json')['points'] if p['id']=='F02'),'old_fit_sha256':h('repaired-fit.json'),'reason':'Independently supported southwest tributary sequence below mill fork, before smaller southern stub and broad downstream eastern reach. Southern interior visibly displaced and lacks nearby support.'});f['points'].append(p);f['status']='Provisional fourteen-control TPS; previous eleven/thirteen fits and all failed evidence remain. Geographic acceptance false.';w('final-fit.json',f)
w('final-freeze.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fit_sha256':h('final-fit.json'),'previous_fit_sha256':h('repaired-fit.json'),'boundary_sha256':hashlib.sha256((D.parent/'boundary.json').read_bytes()).hexdigest(),'control_count':14,'fresh_checks_collected':False,'criteria':{'median_ground_m_max':100,'worst_ground_m_max':200,'distributed_whole_sheet_and_seams_required':True}})
d=r('reused-checks.json');d['points'] += [p for p in v['points'] if p['id']!='F02'];d['fit_sha256']=h('final-fit.json');d['purpose']='Eight reused diagnostic checks, excludes all promoted failures. Q04/Q07 identity caveats retained. No fresh validation claim.';w('final-diagnostic.json',d)
