"""Construct a separate repair from re-inspected physical identities; preserve old evidence."""
from pathlib import Path
import json,hashlib,datetime,copy
D=Path(__file__).resolve().parent;P=D.parent
if (D/'repair-freeze.json').exists():raise SystemExit('Frozen experiment exists; start a new directory.')
r=lambda p:json.loads(p.read_text());h=lambda p:hashlib.file_digest(p.open('rb'),'sha256').hexdigest()
w=lambda n,v:(D/n).write_text(json.dumps(v,indent=2)+'\n')
f=r(P/'regional-fit.json');old=copy.deepcopy(f['points']);v=r(P/'validation-checks.json');s=r(P/'validation-scores.json')
for oid,nid,reason in [('V02','C13','North Brook northern-arm northeastern tributary lies between preceding western tributary and tight southern bend; lower eastern main fork supports network identity. Extra modern downstream parallel branch remains an explicit limitation.'),('V03','C14','McDonald Brook north/east upstream fork lies northeast of the preceding northwestern tributary; long northern reach, east branch ending near road and western downstream bend support identity.')]:
 p=copy.deepcopy(next(p for p in v['points'] if p['id']==oid));p.update(id=nid,role='control',review='Personally re-inspected original unrotated native crosshair close and wide, with marked modern context before repair; coordinates unchanged.',promotion={'old_point':next(p for p in v['points'] if p['id']==oid),'old_result':next(p for p in s['points'] if p['id']==oid),'old_fit_sha256':s['fit_sha256'],'reason':reason,'status':'Permanently diagnostic after promotion; never fresh again.'});f['points'].append(p)
assert f['points'][:11]==old
f['status']='Provisional thirteen-control TPS. All previous eleven controls and all failures preserved. Whole-sheet geography remains unaccepted.'
w('repaired-fit.json',f)
w('repair-freeze.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fit_sha256':h(D/'repaired-fit.json'),'source_sha256':h(Path.home()/'Downloads/fletcher-sheet13/native/sheet13.png'),'boundary_sha256':h(P/'boundary.json'),'prior_fit_sha256':h(P/'regional-fit.json'),'control_count':13,'fresh_validation_collected':False,'criteria':{'median_ground_m_max':100,'worst_ground_m_max':200,'distributed_whole_raster_and_seams_required':True}})
d=r(P/'regional-diagnostics.json');d['points'] += [p for p in v['points'] if p['id'] not in ['V02','V03']];d['fit_sha256']=h(D/'repaired-fit.json');d['purpose']='Six reused checks, never fresh. Q04 and Q07 retain unresolved branch/shape identity limitations. Promoted V02 and V03 excluded.';w('reused-checks.json',d)
w('identity-audit.json',{'reviewed_before_repair':['prior-close/sheet-13-Q04.jpg','prior-wide/sheet-13-Q04.jpg','prior-close/sheet-13-Q07.jpg','prior-wide/sheet-13-Q07.jpg','prior-close/sheet-13-V02.jpg','prior-wide/sheet-13-V02.jpg','prior-close/sheet-13-V03.jpg','prior-wide/sheet-13-V03.jpg'],'Q04':'Retained unchanged as ambiguous reused diagnostic; not promoted. Historical short eastern branch versus modern branching hierarchy not sufficiently established. Error alone cannot resolve identity.','Q07':'Retained unchanged reused diagnostic; not promoted. Modern additional downstream parallel branch remains unexplained.','V02':'Promoted unchanged to C13 after direct close/wide topology review; old failure preserved.','V03':'Promoted unchanged to C14 after direct close/wide topology review; old failure preserved.','boundary':'Original full-scan boundary overview personally viewed. Complete mapped rectangle retained, no new crop or control hull.'})
