"""Freeze the Three Brooks mouth experiment without promoting uncertain old checks."""
from pathlib import Path
import json,hashlib,datetime,copy
D=Path(__file__).resolve().parent;P=D.parent
if (D/'repair-freeze.json').exists():raise SystemExit('Frozen experiment exists; use a new directory.')
r=lambda p:json.loads(p.read_text());h=lambda p:hashlib.file_digest(p.open('rb'),'sha256').hexdigest();w=lambda n,v:(D/n).write_text(json.dumps(v,indent=2)+'\n')
f=r(P/'repaired-fit.json');old=copy.deepcopy(f['points']);rp=r(D/'repair-corrected.json')['points'];p=copy.deepcopy(rp[0]);p.update(id='C13',role='control',status='Personally inspected original and corrected native close/wide crosshairs before fitting. Three Brooks mouth supported by northern main bends, eastern South Branch and next eastern Coulmeach mouth; bank width uncertainty retained.',reviewed_proposal=rp[0]);f['points'].append(p);assert f['points'][:10]==old
f['status']='Provisional eleven-control TPS. Original ten controls preserved; C12 remains explicitly uncertain pending broader topology resolution.';w('repaired-fit.json',f)
w('repair-freeze.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fit_sha256':h(D/'repaired-fit.json'),'prior_fit_sha256':h(P/'repaired-fit.json'),'source_sha256':h(Path.home()/'Downloads/fletcher-sheet08/native/sheet08.png'),'boundary_sha256':h(P/'boundary.json'),'control_count':11,'fresh_validation_collected':False,'criteria':{'median_ground_m_max':100,'worst_ground_m_max':200,'distributed_whole_raster_and_seams_required':True}})
d=r(P/'repair-diagnostic.json');d['points']+=r(P/'validation.json')['points']+[rp[1]];d.update(fit_sha256=h(D/'repaired-fit.json'),purpose='Four reused old checks plus R02 collected before freeze. None is fresh validation. V01 and Coulmeach C12/V03 retain identity concerns.');w('reused-checks.json',d)
w('identity-audit.json',{'R01':'Accepted as C13 after original/corrected close and wide review, Three Brooks eastern mouth with ordered adjacent bends/mouths.','R02':'Pre-freeze Carmruadh/South Branch fork retained as diagnostic only; original and corrected native picks preserved.','V01':'Not promoted: native southern tributary lies west of northern check, while modern southern junction is downstream/east. Branch-order discrepancy unresolved.','C12':'Preserved original fitted record, but larger review does not establish its northern-arm correspondence. Modern arm enters pond terrain; native branch has successive side forks. Neither residual nor name resolves this.','V03':'Local southern junction plausible, but no promotion because adjacent upstream C12 identity is unresolved in broader network. Preserve old failure.','Second Fork':'Regional original/native and modern search inspected; similar fork ordering and reach differences remain unresolved. No control or score adopted.','reservoir_context':'Preserve ../reservoir-caution.md; do not treat changed reservoir outlines as stable shore controls.','boundary':'Original full boundary overview personally inspected; full mapped frame unchanged.'})
