// Generated by scripts/probeGeoPdfFrames.mjs. Do not edit by hand.
import type { ApprovedGeoPdfRule } from "./geoPdfFrameSelection";

export const GEO_PDF_APPROVED_RULES: readonly ApprovedGeoPdfRule[] = [];
