from pathlib import Path
from osgeo import gdal
from PIL import Image,ImageDraw
import json,hashlib,math,numpy as np
from tools.church.geometry import lonlat_to_mercator
R=Path(__file__).resolve().parent;si=json.loads((R/'seam-inputs.json').read_text());s=json.loads((R/'macivers-seam.json').read_text());o=json.loads((R/'observations/IS52-corrected.json').read_text());out=R/'seam-review';out.mkdir(exist_ok=True);p=Path(si['victoria_raster']);assert hashlib.sha256(p.read_bytes()).hexdigest()==si['victoria_raster_sha256'];gdal.UseExceptions();ds=gdal.Open(str(p));lon,lat=s['reference_lonlat'];x,y=lonlat_to_mercator(lon,lat);half=1000/math.cos(math.radians(lat));bounds=[x-half,y-half,x+half,y+half];v=gdal.Warp('',ds,format='MEM',outputBounds=bounds,width=1000,height=1000,resampleAlg='bilinear',dstAlpha=True);im=Image.new('RGBA',(1000,1060),'#efefea');im.alpha_composite(Image.fromarray(np.moveaxis(v.ReadAsArray(),0,2)));d=ImageDraw.Draw(im)
def px(q):return ((q[0]-bounds[0])/(2*half)*1000,(bounds[3]-q[1])/(2*half)*1000)
for f in json.loads(Path(o['reference_path']).read_text())['features']:
 if f['geometry']['type']!='LineString':continue
 a=np.array([lonlat_to_mercator(*q[:2]) for q in f['geometry']['coordinates']]);lo=a.min(axis=0);hi=a.max(axis=0)
 if hi[0]>=bounds[0] and lo[0]<=bounds[2] and hi[1]>=bounds[1] and lo[1]<=bounds[3]:d.line([px(q) for q in a],fill='#0077aa',width=2)
pred=lonlat_to_mercator(*s['victoria_prediction_lonlat']);ax,ay=px(pred);d.line((ax-14,ay-14,ax+14,ay+14),fill='#ec7600',width=3);d.line((ax-14,ay+14,ax+14,ay-14),fill='#ec7600',width=3);d.line((481,500,519,500),fill='red',width=3);d.line((500,481,500,519),fill='red',width=3);d.rectangle((0,1000,1000,1060),fill='#fffdf5');d.text((10,1006),'Victoria main corrected TPS14: existing VM27 diagnostic; 2000 ground-metre window',fill='black');d.text((10,1023),'Orange X: warped source. Red +: shared northwestern corner. Blue: original water.',fill='black');d.text((10,1040),'David Rumsey / Stanford - CC BY-NC-SA 3.0. Reference: original NSTDB.',fill='black');dest=out/'victoria.jpg';im.convert('RGB').save(dest,quality=93);col,row=gdal.ApplyGeoTransform(gdal.InvGeoTransform(ds.GetGeoTransform()),*pred);alpha=int(ds.GetRasterBand(4).ReadAsArray(int(col),int(row),1,1)[0,0]);assert alpha>0
south=R/'warped-review/IS52.jpg';combined=Image.new('RGB',(2000,1060),'white');combined.paste(Image.open(south),(0,0));combined.paste(Image.open(dest),(1000,0));combined.save(out/'side-by-side.jpg',quality=92);receipt={'south_figure':{'path':str(south.relative_to(R)),'sha256':hashlib.sha256(south.read_bytes()).hexdigest()},'victoria_figure':{'path':str(dest.relative_to(R)),'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()},'combined_sha256':hashlib.sha256((out/'side-by-side.jpg').read_bytes()).hexdigest(),'victoria_raster_sha256':si['victoria_raster_sha256'],'victoria_source_pixel_alpha':alpha,'scope':'Actual frozen raster windows at one shared corner; no whole-seam acceptance.'};(out/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print('Paired actual raster review complete')
