from pathlib import Path
import json,hashlib,datetime,shutil,importlib.util
from shapely.geometry import MultiPoint,Point
from tools.church.gcps import GroundControlPoint,load_gcps
R=Path('reports/church/south-western-coast-validation-20260916');assert not R.exists();R.mkdir();(R/'observations').mkdir();(R/'search-evidence').mkdir();C=Path('/Users/dfakkeldy/Downloads/church-south-western-coast-validation-20260916');P=Path('reports/church/south-extension-validation-20260916')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,o):p.write_text(json.dumps(o,indent=2)+'\n')
f=json.loads((P/'freeze.json').read_text());f['input_commit']='df2722b34bd516deaa0eadf5f4d672ca98d9356c'
for key,name in [('controls','controls.csv'),('prior_inventory','fresh-validation.csv'),('prior_accuracy','accuracy-summary.json'),('prior_status','status.json')]:
 p=P/name;f['inputs'][key]={'path':str(p),'sha256':sha(p)}
f['scope']='New Cape Mabou coast checks against unchanged frozen TPS13; preceding fourteen first results retained';save(R/'freeze.json',f);shutil.copy2(P/'controls.csv',R/'controls.csv')
ref=Path('/Users/dfakkeldy/Downloads/church-review-20260913/south-west-water-lines.geojson');green=json.loads((C/'green-western-vertex.json').read_text());sight=json.loads((C/'sight-mouths.json').read_text())[0]
items=[('IS48','green',[786,798],[16336,13048],green['lonlat'],[{'feature_id':green['feature_id'],'vertex':green['vertex']}],'Green Point western shoreline extremum','Local western tip of the headland, north of Mabou Harbour entrance.','The long coast approaches from the north/northeast below Beaton Point, projects west into the distinct Green Point cape, then returns south/southeast toward Mabou Harbour. This coast sequence, the harbour entrance south of the cape and the inland road identify the feature. The original shoreline is more detailed than the engraved apex. The exact original western vertex is used rather than the representative namepoint.','coastal-extremum'),('IS49','sight',[873,629],[17973,9429],sight['lonlat'],[sight['river'],*sight['coast']],'Stream mouth north of Sight Point','Single-line stream/coast junction just north of the Sight Point cape locality.','The creek enters from the southeast, crossing the inland coastal road shortly before meeting the shore. A separate creek mouth lies farther south and another drainage entry lies northeast along the coast. Their order, the winding inland drainage and the parallel road distinguish this mouth. The crosshair lies on the water/coast junction, away from the Sight Point label and the separate road junction. The modern river is unnamed; no stream name is invented.','river-coast-junction')]
obs=[]
for ident,name,display,xy,ll,vertices,label,definition,evidence,kind in items:
 src=C/(name+'-native.jpg');o={'id':ident,'label':label,'role':'check','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_frame':json.loads((C/(name+'-native-frame.json')).read_text()),'source_crop_path':str(src),'source_crop_sha256':sha(src),'source_sha256':'37021ed086f7bbce542b519e9a74242acc5b53ed1944880468f6f91d6234a7f8','source_display_pixel_xy':display,'pixel_xy':xy,'lonlat':ll,'reference_path':str(ref),'reference_sha256':sha(ref),'reference_vertices':vertices,'reference_kind':kind,'uncertainty_ground_m':150,'point_definition':definition,'identity_evidence':evidence,'phase':'Fresh independent validation of frozen TPS13; excluded from fitting and model selection'};save(R/'observations'/(ident+'.json'),o);obs.append(o)
 for a,b in [(name+'-proposal.jpg',ident+'-native-review.jpg'),(name+'-proposal-detail.jpg',ident+'-native-enlarged.jpg')]:shutil.copy2(C/a,R/'observations'/b)
for p in C.iterdir():
 if p.suffix in ['.py','.json','.jpg','.geojson']:shutil.copy2(p,R/'search-evidence'/p.name)
cs=load_gcps(R/'controls.csv');prior=[p for p in load_gcps(P/'fresh-validation.csv') if p.role=='check'];base=load_gcps(Path(f['inputs']['baseline_controls']['path']));hull=MultiPoint([(q.pixel_x,q.pixel_y) for q in cs]).convex_hull;s=importlib.util.spec_from_file_location('score',R.parent/'target-refinement-20260913/score_models.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);new=[]
for o in obs:
 p=GroundControlPoint(*o['pixel_xy'],*o['lonlat'],'check',o['id']);new.append(p);first={'scored_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observation_sha256':sha(R/'observations'/(o['id']+'.json')),'freeze_sha256':sha(R/'freeze.json'),'inside_control_hull':hull.covers(Point(*o['pixel_xy'])),'physical_tps13':m.score(cs,[p],'tps'),'accepted_baseline_tps':m.score(base,[p],'tps')};save(R/(o['id']+'-first.json'),first);print(o['id'],first['physical_tps13']['rms_ground_m'],first['accepted_baseline_tps']['rms_ground_m'],'inside',first['inside_control_hull'])
rows=''.join(f'{p.pixel_x},{p.pixel_y},{p.lon},{p.lat},check,{p.label}\n' for p in new);(R/'fresh-validation.csv').write_text((P/'fresh-validation.csv').read_text()+rows);(R/'new-checks.csv').write_text((P/'controls.csv').read_text()+rows);a={'physical_tps13':m.score(cs,prior+new,'tps'),'accepted_baseline_tps':m.score(base,prior+new,'tps'),'new_pair_tps13':m.score(cs,new,'tps'),'new_pair_baseline':m.score(base,new,'tps')};save(R/'accuracy-summary.json',a);print(json.dumps({k:{kk:vv for kk,vv in v.items() if kk!='points'} for k,v in a.items()},indent=2))
