import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

export const REQUIRED_HOLDOUTS_PER_SIGNATURE = 2;

export function buildNeatlineArgs(pdfPath, label) {
  return ["-json", "-oo", `NEATLINE=${label}`, pdfPath];
}

export function exactSelectorSignature({
  producer,
  family,
  structureId,
  labels,
}) {
  return [
    producer,
    family,
    structureId,
    [...labels].sort().join("\u001f"),
  ].join("|");
}

export function validateHoldoutRows(rows, requiredSignatures) {
  const grouped = Map.groupBy(rows, (row) => row.signature);
  for (const signature of requiredSignatures) {
    const signatureRows = grouped.get(signature) ?? [];
    const falseSelections = signatureRows.filter(
      (row) => row.result === "false-selection",
    );
    if (falseSelections.length > 0) {
      return {
        approved: false,
        reason: `${signature} has ${falseSelections.length} false selection${
          falseSelections.length === 1 ? "" : "s"
        }`,
      };
    }

    const passingHoldouts = signatureRows.filter(
      (row) => row.role === "holdout" && row.result === "pass",
    );
    const distinctHoldouts = new Set(
      passingHoldouts.map((row) => `${row.sha256}\u001f${row.productId}`),
    ).size;
    if (distinctHoldouts < REQUIRED_HOLDOUTS_PER_SIGNATURE) {
      return {
        approved: false,
        reason: `${signature} has ${distinctHoldouts} passing holdout${
          distinctHoldouts === 1 ? "" : "s"
        }; ${REQUIRED_HOLDOUTS_PER_SIGNATURE} required`,
      };
    }
  }
  return { approved: true };
}

export function approvedRulesFromReceipt(receipt) {
  return receipt.signatures
    .filter(({ signature }) =>
      validateHoldoutRows(receipt.rows, [signature]).approved
    )
    .map(({ signature, selectedEmbeddedLabel }) => ({
      signature,
      selectedEmbeddedLabel,
    }))
    .sort((left, right) => left.signature.localeCompare(right.signature));
}

export function renderApprovedRulesModule(rules) {
  const serialized = rules.length === 0
    ? "[]"
    : JSON.stringify(rules, null, 2);
  return [
    "// Generated by scripts/probeGeoPdfFrames.mjs. Do not edit by hand.",
    'import type { GeoPdfApprovedRule } from "./geoPdfFrameSelection";',
    "",
    `export const GEO_PDF_APPROVED_RULES: readonly GeoPdfApprovedRule[] = ${serialized};`,
    "",
  ].join("\n");
}

function valueAfter(args, flag) {
  const index = args.indexOf(flag);
  return index === -1 ? null : args[index + 1] ?? null;
}

async function main(args) {
  const receiptPath = valueAfter(args, "--approved-rules-from");
  const targetPath = valueAfter(args, "--write-approved-rules");
  if (!receiptPath || !targetPath) {
    throw new Error(
      "usage: node scripts/probeGeoPdfFrames.mjs " +
      "--approved-rules-from <receipt.json> --write-approved-rules <target.ts>",
    );
  }

  const receipt = JSON.parse(await readFile(receiptPath, "utf8"));
  const rules = approvedRulesFromReceipt(receipt);
  await writeFile(targetPath, renderApprovedRulesModule(rules));
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main(process.argv.slice(2));
}
