import assert from "node:assert/strict";
import { test } from "node:test";
import {
  approvedRulesFromReceipt,
  buildNeatlineArgs,
  exactSelectorSignature,
  renderApprovedRulesModule,
  validateHoldoutRows,
} from "./probeGeoPdfFrames.mjs";

test("opens each named registration through GDAL's NEATLINE option", () => {
  assert.deepEqual(
    buildNeatlineArgs("/tmp/usgs.pdf", "Map Layers"),
    ["-json", "-oo", "NEATLINE=Map Layers", "/tmp/usgs.pdf"],
  );
});

test("signature includes producer, family, structure, and full label multiset", () => {
  assert.equal(
    exactSelectorSignature({
      producer: "Esri ArcSOC 10.8.1.14362",
      family: "measure",
      structureId: "measure-vp-geo-v1",
      labels: [
        "Quadrangle Location",
        "Map Layers",
        "Adjoining Sheet Diagram",
      ],
    }),
    [
      "Esri ArcSOC 10.8.1.14362",
      "measure",
      "measure-vp-geo-v1",
      "Adjoining Sheet Diagram\u001fMap Layers\u001fQuadrangle Location",
    ].join("|"),
  );
});

test("requires two distinct untouched passing holdouts", () => {
  assert.deepEqual(
    validateHoldoutRows(
      [
        {
          signature: "modern-3",
          role: "holdout",
          sha256: "aaa",
          productId: "quadrangle-a",
          result: "pass",
        },
      ],
      ["modern-3"],
    ),
    {
      approved: false,
      reason: "modern-3 has 1 passing holdout; 2 required",
    },
  );
});

test("does not double-count the same holdout product", () => {
  const duplicate = {
    signature: "modern-3",
    role: "holdout",
    sha256: "aaa",
    productId: "quadrangle-a",
    result: "pass",
  };
  assert.equal(
    validateHoldoutRows([duplicate, duplicate], ["modern-3"]).approved,
    false,
  );
});

test("one false selection refuses an otherwise sufficient signature", () => {
  assert.deepEqual(
    validateHoldoutRows(
      [
        {
          signature: "modern-3",
          role: "holdout",
          sha256: "aaa",
          productId: "quadrangle-a",
          result: "pass",
        },
        {
          signature: "modern-3",
          role: "holdout",
          sha256: "bbb",
          productId: "quadrangle-b",
          result: "pass",
        },
        {
          signature: "modern-3",
          role: "discovery",
          sha256: "ccc",
          productId: "quadrangle-c",
          result: "false-selection",
        },
      ],
      ["modern-3"],
    ),
    {
      approved: false,
      reason: "modern-3 has 1 false selection",
    },
  );
});

test("emits no automatic rules when the receipt has no qualified holdouts", () => {
  assert.deepEqual(
    approvedRulesFromReceipt({
      signatures: [
        {
          signature: "modern-3",
          selectedEmbeddedLabel: "Map Layers",
        },
      ],
      rows: [],
    }),
    [],
  );
});

test("emits only exact signatures that pass the evidence gate", () => {
  assert.deepEqual(
    approvedRulesFromReceipt({
      signatures: [
        {
          signature: "modern-3",
          selectedEmbeddedLabel: "Map Layers",
        },
      ],
      rows: [
        {
          signature: "modern-3",
          role: "holdout",
          sha256: "aaa",
          productId: "quadrangle-a",
          result: "pass",
        },
        {
          signature: "modern-3",
          role: "holdout",
          sha256: "bbb",
          productId: "quadrangle-b",
          result: "pass",
        },
      ],
    }),
    [
      {
        signature: "modern-3",
        selectedEmbeddedLabel: "Map Layers",
      },
    ],
  );
});

test("renders a stable TypeScript module from approved rules", () => {
  assert.equal(
    renderApprovedRulesModule([]),
    [
      "// Generated by scripts/probeGeoPdfFrames.mjs. Do not edit by hand.",
      'import type { ApprovedGeoPdfRule } from "./geoPdfFrameSelection";',
      "",
      "export const GEO_PDF_APPROVED_RULES: readonly ApprovedGeoPdfRule[] = [];",
      "",
    ].join("\n"),
  );
});
