import { chromium } from '../../../web/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
const [raster, out, position] = process.argv.slice(2);
if (!raster || !out) throw new Error('Usage: node verify-browser.mjs RASTER OUTPUT_DIRECTORY');
const name=raster.split('/').pop().replace(/\.tif$/i,'');
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push({kind:'pageerror',message:e.message}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:m.text()})});
await page.addInitScript(()=>localStorage.setItem('ns-marks-the-spot:province-license:v1','accepted'));
await page.goto(`http://127.0.0.1:4198/?basemap=osm&taxSale=off&layers=modern&position=${position}`);
await page.getByRole('button',{name:/^My Maps/}).click();
await page.getByLabel('Add a map file',{exact:true}).setInputFiles(raster);
await page.getByRole('checkbox',{name,exact:true}).waitFor({timeout:180000});
console.log('imported');
await page.getByRole('checkbox',{name,exact:true}).check();
await page.waitForFunction(()=>{const c=document.querySelector('.leaflet-user-maps-pane-pane canvas');if(!c)return false;return c.width>0&&c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)}, {timeout:60000});
async function storedProof(){return await page.evaluate(async()=>{
 const {UserMapStore}=await import('/src/userMaps/store/userMapStore.ts');
 const store=await UserMapStore.open();const records=await store.listUserMaps();const record=records[0];const blob=await store.getRasterBlob(record.id);
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(n=>n.toString(16).padStart(2,'0')).join('');
 const preview=await store.getPreviewBlob(record.id);const bitmap=await createImageBitmap(preview);const previewSize=[bitmap.width,bitmap.height];const canvas=new OffscreenCanvas(bitmap.width,bitmap.height);const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0);const data=ctx.getImageData(0,0,bitmap.width,bitmap.height).data;let transparent=0,opaque=0;for(let i=3;i<data.length;i+=4){if(data[i]===0)transparent++;if(data[i]===255)opaque++}bitmap.close();store.close();
 return {record,previewSize,storedRasterSha256:hash,rasterBytes:blob.size,rasterMime:blob.type,transparentPixels:transparent,opaquePixels:opaque};
})}
const before=await storedProof(); if(before.storedRasterSha256 !== (await import('node:crypto')).createHash('sha256').update(await fs.readFile(raster)).digest('hex')) throw new Error('Wrong raster hash');
await fs.writeFile(out+'/import.txt',await page.locator('body').innerText());
await page.getByText('Loading visible area…',{exact:true}).waitFor({state:'hidden',timeout:60000});
await page.screenshot({path:out+'/import-desktop.png'});
const records=await page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('ns-marks-the-spot-user-maps');req.onsuccess=()=>{const db=req.result;const r=db.transaction('maps').objectStore('maps').getAll();r.onsuccess=()=>{db.close();resolve(r.result)};r.onerror=()=>reject(r.error)}}));
await fs.writeFile(out+'/records.json',JSON.stringify(records,null,2));
await page.reload();
await page.getByRole('button',{name:/^My Maps/}).click();
await page.getByRole('checkbox',{name,exact:true}).waitFor();
if(!await page.getByRole('checkbox',{name,exact:true}).isChecked())throw new Error('Enabled state did not survive reload');
await page.waitForFunction(()=>{const c=document.querySelector('.leaflet-user-maps-pane-pane canvas');if(!c)return false;return c.width>0&&c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)});
const after=await storedProof();if(before.storedRasterSha256!==after.storedRasterSha256)throw new Error('Raster hash changed on reload');
await fs.writeFile(out+'/verification.json',JSON.stringify({tooling:'Playwright; Browser plugin not available',before,after,enabledStateSurvived:true},null,2));
await page.screenshot({path:out+'/reload-desktop.png'});
await fs.writeFile(out+'/reload.txt',await page.locator('body').innerText());
await page.setViewportSize({width:390,height:844});
await page.reload();
await page.waitForFunction(()=>{const c=document.querySelector('.leaflet-user-maps-pane-pane canvas');return c&&c.width>0&&c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)});
const mobile=await storedProof();if(mobile.storedRasterSha256!==before.storedRasterSha256)throw new Error('Mobile reload changed raster bytes');
await fs.writeFile(out+'/mobile-verification.json',JSON.stringify(mobile,null,2));
await page.screenshot({path:out+'/reload-mobile.png'});
await page.setViewportSize({width:1440,height:1000});
await fs.writeFile(out+'/errors.json',JSON.stringify(errors,null,2));
console.log(JSON.stringify({url:page.url(),title:await page.title(),records:records.length,errors}));
await browser.close();
if(errors.length)throw new Error('Browser console errors: '+JSON.stringify(errors));
