from pathlib import Path
import json,hashlib,datetime,shutil,importlib.util
from shapely.geometry import MultiPoint,Point
from tools.church.gcps import GroundControlPoint,load_gcps
R=Path('reports/church/south-extension-validation-20260916');assert not R.exists();R.mkdir();(R/'observations').mkdir();(R/'search-evidence').mkdir();C=Path('/Users/dfakkeldy/Downloads/church-south-extension-validation-20260916');P=Path('reports/church/south-southern-validation-20260916')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,o):p.write_text(json.dumps(o,indent=2)+'\n')
f=json.loads((P/'freeze.json').read_text());f['input_commit']='c95312709514bd62c3e4e067c2324070e2137a2a'
for key,name in [('controls','controls.csv'),('prior_inventory','fresh-validation.csv'),('prior_accuracy','accuracy-summary.json'),('prior_status','status.json')]:
 p=P/name;f['inputs'][key]={'path':str(p),'sha256':sha(p)}
f['scope']='New southern-extension check against unchanged frozen TPS13; preceding thirteen first results retained';save(R/'freeze.json',f);shutil.copy2(P/'controls.csv',R/'controls.csv')
q=json.loads((C/'all-junction-search.json').read_text())[3];src=C/'north-little-native.jpg';ref=C/'extension-water-lines.geojson'
o={'id':'IS47','label':'North Little River / engraved South Branch confluence','role':'check','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_frame':json.loads((C/'north-little-native-frame.json').read_text()),'source_crop_path':str(src),'source_crop_sha256':sha(src),'source_sha256':'37021ed086f7bbce542b519e9a74242acc5b53ed1944880468f6f91d6234a7f8','source_display_pixel_xy':[884,708],'pixel_xy':[21084,31608],'lonlat':q['lonlat'],'reference_path':str(ref),'reference_sha256':sha(ref),'reference_vertices':[{'feature_id':v['feature_id'],'vertex':v['vertex']} for v in q['branches']],'reference_kind':'Original single-line water confluence','uncertainty_ground_m':150,'point_definition':'Long western tributary meets the northwest main channel; combined river continues southeast before a separate southern tributary and eastward bend.','identity_evidence':'The northwestern approach bends south into a clearly drawn junction. The long western branch has the same broad upstream northward bow; the joined channel goes southeast to a separate southern tributary, then bends east. Source labels North Branch, South Branch and Little River corroborate the topology. The western reference tributary has a blank name field, so no modern South Branch name is asserted. The crosshair is on the three-way water-line convergence, separate from lettering and the downstream road crossing.','phase':'Fresh independent validation of frozen TPS13; excluded from fitting and selection'};save(R/'observations/IS47.json',o)
for a,b in [('north-little-proposal.jpg','IS47-native-review.jpg'),('north-little-proposal-detail.jpg','IS47-native-enlarged.jpg')]:shutil.copy2(C/a,R/'observations'/b)
for p in C.iterdir():
 if p.suffix in ['.py','.json','.jpg']:shutil.copy2(p,R/'search-evidence'/p.name)
cs=load_gcps(R/'controls.csv');prior=[p for p in load_gcps(P/'fresh-validation.csv') if p.role=='check'];base=load_gcps(Path(f['inputs']['baseline_controls']['path']));p=GroundControlPoint(*o['pixel_xy'],*o['lonlat'],'check','IS47');s=importlib.util.spec_from_file_location('score',R.parent/'target-refinement-20260913/score_models.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
first={'scored_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observation_sha256':sha(R/'observations/IS47.json'),'freeze_sha256':sha(R/'freeze.json'),'inside_control_hull':MultiPoint([(q.pixel_x,q.pixel_y) for q in cs]).convex_hull.covers(Point(*o['pixel_xy'])),'physical_tps13':m.score(cs,[p],'tps'),'accepted_baseline_tps':m.score(base,[p],'tps')};save(R/'IS47-first.json',first)
row=f'{p.pixel_x},{p.pixel_y},{p.lon},{p.lat},check,IS47\n';(R/'fresh-validation.csv').write_text((P/'fresh-validation.csv').read_text()+row);(R/'new-check.csv').write_text((P/'controls.csv').read_text()+row);a={'physical_tps13':m.score(cs,prior+[p],'tps'),'accepted_baseline_tps':m.score(base,prior+[p],'tps')};save(R/'accuracy-summary.json',a);print(json.dumps({'first':first,'cumulative':{k:v for k,v in a['physical_tps13'].items() if k!='points'}},indent=2))
