from pathlib import Path
import json,hashlib,datetime,shutil,importlib.util
from shapely.geometry import MultiPoint,Point
from tools.church.gcps import GroundControlPoint,load_gcps
R=Path('reports/church/south-northeast-validation-20260916');assert not R.exists();R.mkdir();(R/'observations').mkdir();(R/'search-evidence').mkdir();C=Path('/Users/dfakkeldy/Downloads/church-south-northeast-validation-20260916');P=Path('reports/church/south-western-coast-validation-20260916')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,o):p.write_text(json.dumps(o,indent=2)+'\n')
f=json.loads((P/'freeze.json').read_text());f['input_commit']='749036f0f3e3936b5160098da6c69b1337a97b19'
for key,name in [('controls','controls.csv'),('prior_inventory','fresh-validation.csv'),('prior_accuracy','accuracy-summary.json'),('prior_status','status.json')]:
 p=P/name;f['inputs'][key]={'path':str(p),'sha256':sha(p)}
f['scope']='New northeastern interior checks against unchanged frozen TPS13; preceding sixteen first results retained';save(R/'freeze.json',f);shutil.copy2(P/'controls.csv',R/'controls.csv')
ref=Path('/Users/dfakkeldy/Downloads/church-georeferencing-20260912/reference/water-lines.geojson');search=json.loads((C/'named-junction-search.json').read_text());items=[('IS50','nile',3,[562,452],[31762,3252],'Nile Brook / South Nile Brook confluence','North-going source branch and eastern South Branch meet, with the combined channel continuing west.','The source labels North Branch Nile Brook and South Branch, and shows the northern channel swinging west, east and west again before joining the eastern branch. The southern branch bows southeast farther upstream, and the joined stream runs west through the valley flank. This matches the original named network and neighbouring drainage. A fourth, smaller unnamed reference tributary shares the node but is not clearly drawn in the historical scan; it is not used as an independent matching feature. The chosen pixel is the clear main-branch convergence, away from lettering and hatching.'),('IS51','gallant',9,[614,367],[29014,1367],'Gallant River / Deep Brook confluence','Eastern tributary enters the north-south river above its separate downstream road crossing.','The river approaches from the north beside the road; the road turns east while the river continues south to meet an eastern tributary. Below the junction the river bends southwest across a separate road crossing and continues west. The upstream eastern branch and neighbouring road configuration match the original network. The junction is visible east of the separate sawmill symbol, not at that symbol or at the lower road crossing.')];obs=[]
for ident,name,index,display,xy,label,definition,evidence in items:
 q=search[index];src=C/(name+'-native.jpg');o={'id':ident,'label':label,'role':'check','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_frame':json.loads((C/(name+'-native-frame.json')).read_text()),'source_crop_path':str(src),'source_crop_sha256':sha(src),'source_sha256':'37021ed086f7bbce542b519e9a74242acc5b53ed1944880468f6f91d6234a7f8','source_display_pixel_xy':display,'pixel_xy':xy,'lonlat':q['lonlat'],'reference_path':str(ref),'reference_sha256':sha(ref),'reference_vertices':[{'feature_id':v['feature_id'],'vertex':v['vertex']} for v in q['branches']],'reference_kind':'Original single-line water confluence','uncertainty_ground_m':150,'point_definition':definition,'identity_evidence':evidence,'phase':'Fresh independent validation of frozen TPS13; excluded from fitting and selection'};save(R/'observations'/(ident+'.json'),o);obs.append(o)
 for a,b in [(name+'-proposal.jpg',ident+'-native-review.jpg'),(name+'-proposal-detail.jpg',ident+'-native-enlarged.jpg')]:shutil.copy2(C/a,R/'observations'/b)
for p in C.iterdir():
 if p.suffix in ['.py','.json','.jpg']:shutil.copy2(p,R/'search-evidence'/p.name)
cs=load_gcps(R/'controls.csv');prior=[p for p in load_gcps(P/'fresh-validation.csv') if p.role=='check'];base=load_gcps(Path(f['inputs']['baseline_controls']['path']));hull=MultiPoint([(q.pixel_x,q.pixel_y) for q in cs]).convex_hull;s=importlib.util.spec_from_file_location('score',R.parent/'target-refinement-20260913/score_models.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);new=[]
for o in obs:
 p=GroundControlPoint(*o['pixel_xy'],*o['lonlat'],'check',o['id']);new.append(p);first={'scored_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observation_sha256':sha(R/'observations'/(o['id']+'.json')),'freeze_sha256':sha(R/'freeze.json'),'inside_control_hull':hull.covers(Point(*o['pixel_xy'])),'physical_tps13':m.score(cs,[p],'tps'),'accepted_baseline_tps':m.score(base,[p],'tps')};save(R/(o['id']+'-first.json'),first);print(o['id'],first['physical_tps13']['rms_ground_m'],first['accepted_baseline_tps']['rms_ground_m'],'inside',first['inside_control_hull'])
rows=''.join(f'{p.pixel_x},{p.pixel_y},{p.lon},{p.lat},check,{p.label}\n' for p in new);(R/'fresh-validation.csv').write_text((P/'fresh-validation.csv').read_text()+rows);(R/'new-checks.csv').write_text((P/'controls.csv').read_text()+rows);a={'physical_tps13':m.score(cs,prior+new,'tps'),'accepted_baseline_tps':m.score(base,prior+new,'tps'),'new_pair_tps13':m.score(cs,new,'tps'),'new_pair_baseline':m.score(base,new,'tps')};save(R/'accuracy-summary.json',a);print(json.dumps({k:{kk:vv for kk,vv in v.items() if kk!='points'} for k,v in a.items()},indent=2))
