from pathlib import Path
import json,hashlib,datetime,shutil,importlib.util
from shapely.geometry import MultiPoint,Point
from tools.church.gcps import GroundControlPoint,load_gcps
R=Path('reports/church/south-eastern-coverage-validation-20260916');assert not R.exists();R.mkdir();(R/'observations').mkdir();(R/'search-evidence').mkdir();C=Path('/Users/dfakkeldy/Downloads/church-south-eastern-coverage-validation-20260916');P=Path('reports/church/south-northeast-validation-20260916')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,o):p.write_text(json.dumps(o,indent=2)+'\n')
f=json.loads((P/'freeze.json').read_text());f['input_commit']='c7f0242ffab658f64e13378beb1484fc736aa9ef'
for key,name in [('controls','controls.csv'),('prior_inventory','fresh-validation.csv'),('prior_accuracy','accuracy-summary.json'),('prior_status','status.json')]:
 p=P/name;f['inputs'][key]={'path':str(p),'sha256':sha(p)}
f['scope']='New eastern-shore checks against unchanged frozen TPS13; preceding eighteen first results retained';save(R/'freeze.json',f);shutil.copy2(P/'controls.csv',R/'controls.csv')
ref=Path('/Users/dfakkeldy/Downloads/church-georeferencing-20260912/reference/water-lines.geojson');search=json.loads((C/'proposed-extrema.json').read_text());items=[('IS52','maciver',[32016,15429],'MacIvers Point western shoreline extremum',200,'west','The west-facing headland has a notched northern shore, a western front and a southern return into MacDonald Cove. The long cove and the opposing channel shore identify the feature independently of the namepoint. The engraved front is more angular than the original modern shoreline; the western extremum is the shared definition and uncertainty is 200 m. The modern name record is in Victoria County, but this adjacent shore is explicitly drawn inside the Inverness south main-map content and cutline.'),('IS53','malagawatch',[32355,22356],'Malagawatch Point eastern shoreline extremum',150,'east','The peninsula approaches from the west and curves around its eastern face into a long northwestern hook, with the enclosed cove, detached islets to the northwest and the southern harbour shore in the same sequence. The eastern outer-coast extremum is clear away from the label. The interior ponds and finer modern shoreline details are not substituted for the outer coast.')];obs=[]
for ident,name,xy,label,unc,direction,evidence in items:
 q=next(q for q in search if q['name']==name);src=C/(name+'-native.jpg');o={'id':ident,'label':label,'role':'check','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_frame':json.loads((C/(name+'-native-frame.json')).read_text()),'source_crop_path':str(src),'source_crop_sha256':sha(src),'source_sha256':'37021ed086f7bbce542b519e9a74242acc5b53ed1944880468f6f91d6234a7f8','source_display_pixel_xy':q['source_display_pixel_xy'],'pixel_xy':xy,'lonlat':q['lonlat'],'reference_path':str(ref),'reference_sha256':sha(ref),'reference_vertices':[{'feature_id':q['feature_id'],'vertex':q['vertex']}],'reference_kind':'coastal-extremum','extremum_direction':direction,'uncertainty_ground_m':unc,'point_definition':q['definition'],'identity_evidence':evidence,'phase':'Fresh independent validation of frozen TPS13; excluded from fitting and selection'};save(R/'observations'/(ident+'.json'),o);obs.append(o)
 for a,b in [(name+'-proposal.jpg',ident+'-native-review.jpg'),(name+'-proposal-detail.jpg',ident+'-native-enlarged.jpg'),(name+'-reference-proposal.jpg',ident+'-prescore-reference-review.jpg')]:shutil.copy2(C/a,R/'observations'/b)
for p in C.iterdir():
 if p.suffix in ['.py','.json','.jpg','.geojson']:shutil.copy2(p,R/'search-evidence'/p.name)
cs=load_gcps(R/'controls.csv');prior=[p for p in load_gcps(P/'fresh-validation.csv') if p.role=='check'];base=load_gcps(Path(f['inputs']['baseline_controls']['path']));hull=MultiPoint([(q.pixel_x,q.pixel_y) for q in cs]).convex_hull;s=importlib.util.spec_from_file_location('score',R.parent/'target-refinement-20260913/score_models.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);new=[]
for o in obs:
 p=GroundControlPoint(*o['pixel_xy'],*o['lonlat'],'check',o['id']);new.append(p);first={'scored_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observation_sha256':sha(R/'observations'/(o['id']+'.json')),'freeze_sha256':sha(R/'freeze.json'),'inside_control_hull':hull.covers(Point(*o['pixel_xy'])),'physical_tps13':m.score(cs,[p],'tps'),'accepted_baseline_tps':m.score(base,[p],'tps')};save(R/(o['id']+'-first.json'),first);print(o['id'],first['physical_tps13']['rms_ground_m'],first['accepted_baseline_tps']['rms_ground_m'],'inside',first['inside_control_hull'])
rows=''.join(f'{p.pixel_x},{p.pixel_y},{p.lon},{p.lat},check,{p.label}\n' for p in new);(R/'fresh-validation.csv').write_text((P/'fresh-validation.csv').read_text()+rows);(R/'new-checks.csv').write_text((P/'controls.csv').read_text()+rows);a={'physical_tps13':m.score(cs,prior+new,'tps'),'accepted_baseline_tps':m.score(base,prior+new,'tps'),'new_pair_tps13':m.score(cs,new,'tps'),'new_pair_baseline':m.score(base,new,'tps')};save(R/'accuracy-summary.json',a);print(json.dumps({k:{kk:vv for kk,vv in v.items() if kk!='points'} for k,v in a.items()},indent=2))
