"""Freeze a western Sheet11 repair while retaining failed prior checks verbatim."""
from pathlib import Path
import json,hashlib,datetime,copy
D=Path(__file__).resolve().parent;P=D.parent/'completion-20260911'
if (D/'repair-freeze.json').exists():raise SystemExit('Frozen fit exists; preserve it and use a new directory.')
r=lambda p:json.loads(p.read_text());h=lambda p:hashlib.file_digest(p.open('rb'),'sha256').hexdigest();w=lambda n,v:(D/n).write_text(json.dumps(v,indent=2)+'\n')
f=r(P/'western-fit.json');old=copy.deepcopy(f['points'])
for id,newid,checks,scores in [('Q04','W04','western-diagnostics.json','western-diagnostic-scores.json'),('V06','W05','western-validation-checks.json','western-validation-scores.json')]:
 oldpoint=next(p for p in r(P/checks)['points'] if p['id']==id);p=copy.deepcopy(oldpoint);p.update(id=newid,role='control',promotion={'old_point':oldpoint,'old_result':next(p for p in r(P/scores)['points'] if p['id']==id),'review':'Personally inspected unchanged original native close/wide crosshairs and marked modern drainage/shore context before this freeze; explicit promotion after prior failed validation.'});f['points'].append(p)
assert f['points'][:26]==old
f['status']='Provisional twenty-eight-control western repair; no geographic acceptance';w('repaired-fit.json',f)
w('repair-freeze.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fit_sha256':h(D/'repaired-fit.json'),'prior_fit_sha256':h(P/'western-fit.json'),'source_sha256':h(Path.home()/'Downloads/fletcher-sheet11/native/sheet11.png'),'boundaries':[{'component':n,'sha256':h(D.parent/f'boundary-{n}.json')} for n in ['mainland','island']],'control_count':28,'fresh_validation_collected':False,'criteria':{'median_ground_m_max':100,'worst_ground_m_max':200,'distributed_whole_raster_and_seams_required':True}})
diag=r(P/'western-diagnostics.json');diag['points']=[p for p in diag['points'] if p['id']!='Q04']+[p for p in r(P/'western-validation-checks.json')['points'] if p['id']=='V07'];diag.update(fit_sha256=h(D/'repaired-fit.json'),status='Ten reused diagnostics; V07 bank/channel identity and Q03 Grey headwater identity unresolved. Not fresh validation.');w('reused-checks.json',diag)
w('identity-audit.json',{'Q04':'Promoted unchanged to W04: short paired headwater arms, downstream coast-road crossing and coastal mouth support identity. Prior 174.24 m failure retained.','V06':'Promoted unchanged to W05: first small eastern branch below coastal mouth and above later paired W03 forks; main-channel bends and coast/road context support identity. Prior 154.08 m failure retained.','V07':'Not promoted: native bank entry beside loop/cutoff and small island differs from modern island/channel configuration; residual is not a clean transform-error measurement. Neither coordinate moved.','Q03':'Not promoted: close native paired headwater branches and modern separated junctions remain ambiguous under geological hatching. Small residual does not establish identity.','boundary':'Original full mainland mapped extension and separate Sea Wolf Island including its printed name personally reviewed; both boundaries unchanged.'})
