raise SystemExit('Archived adoption recipe; use verify_reports.py to replay preserved results.')
from pathlib import Path
import json,hashlib,datetime,shutil,importlib.util
from shapely.geometry import MultiPoint,Point
from tools.church.gcps import GroundControlPoint,load_gcps
R=Path('reports/church/south-southern-validation-20260916');C=Path('/Users/dfakkeldy/Downloads/church-south-southern-validation-20260916')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,o):p.write_text(json.dumps(o,indent=2)+'\n')
q=json.loads((C/'named-junction-search.json').read_text())[3];src=C/'glendale.jpg';ref=Path('/Users/dfakkeldy/Downloads/church-south-validation-20260915/southwest-water-lines.geojson')
o={'id':'IS46','label':'MacColls Brook / River Inhabitants confluence','role':'check','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_frame':json.loads((C/'glendale-frame.json').read_text()),'source_crop_path':str(src),'source_crop_sha256':sha(src),'source_sha256':'37021ed086f7bbce542b519e9a74242acc5b53ed1944880468f6f91d6234a7f8','source_display_pixel_xy':[873,992],'pixel_xy':[20773,24792],'lonlat':q['lonlat'],'reference_path':str(ref),'reference_sha256':sha(ref),'reference_vertices':[{'feature_id':v['feature_id'],'vertex':v['vertex']} for v in q['branches']],'reference_kind':'Original single-line water confluence','uncertainty_ground_m':180,'point_definition':'Northern tributary enters the main east-west river east/upstream of the separate Glendale Brook junction.','identity_evidence':'The northern tributary has a small split/rejoining reach farther north and crosses the east-west road before entering the river. The main river approaches from the east through the separately marked falls reach, and continues west/southwest toward Glendale and Red Bridge. Glendale Brook enters farther west near dense road/label ink, so that separate junction is withheld. The exact MacColls junction is clear south of the road and north of the chapel lettering. Current road realignments are not used as matching nodes. Native crosshair and marked original reference junction were inspected before scoring.','phase':'Fresh independent validation of frozen TPS13; excluded from fitting and model selection'};save(R/'observations/IS46.json',o)
for a,b in [('maccolls-proposal.jpg','IS46-native-review.jpg'),('maccolls-proposal-detail.jpg','IS46-native-enlarged.jpg')]:shutil.copy2(C/a,R/'observations'/b)
for p in C.iterdir():
 if p.suffix in ['.py','.json','.jpg'] and not (R/'search-evidence'/p.name).exists():shutil.copy2(p,R/'search-evidence'/p.name)
save(R/'search-evidence/withheld-glendale.json',{'feature':'Glendale Brook / River Inhabitants','reference_lonlat':[-61.32065670986413,45.811328240692056],'status':'withheld-unscored','reason':'Separate western junction lies amid dense road and lettering ink. The clearer eastern MacColls junction was adopted instead; they are not aliases.'})
for a,b in [('fresh-validation.csv','first-twelve.csv'),('accuracy-summary.json','first-twelve-summary.json'),('new-check.csv','first-new-check.csv')]:shutil.copy2(R/a,R/b)
f=json.loads((R/'freeze.json').read_text());cs=load_gcps(R/'controls.csv');prior=[p for p in load_gcps(R/'fresh-validation.csv') if p.role=='check'];base=load_gcps(Path(f['inputs']['baseline_controls']['path']));p=GroundControlPoint(*o['pixel_xy'],*o['lonlat'],'check','IS46');s=importlib.util.spec_from_file_location('score',R.parent/'target-refinement-20260913/score_models.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
first={'scored_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observation_sha256':sha(R/'observations/IS46.json'),'freeze_sha256':sha(R/'freeze.json'),'inside_control_hull':MultiPoint([(q.pixel_x,q.pixel_y) for q in cs]).convex_hull.covers(Point(*o['pixel_xy'])),'physical_tps13':m.score(cs,[p],'tps'),'accepted_baseline_tps':m.score(base,[p],'tps')};save(R/'IS46-first.json',first)
row=f'{p.pixel_x},{p.pixel_y},{p.lon},{p.lat},check,IS46\n';(R/'fresh-validation.csv').write_text((R/'fresh-validation.csv').read_text()+row);(R/'new-check.csv').write_text((R/'new-check.csv').read_text()+row);new=prior[-1:]+[p];a={'physical_tps13':m.score(cs,prior+[p],'tps'),'accepted_baseline_tps':m.score(base,prior+[p],'tps'),'new_pair_tps13':m.score(cs,new,'tps'),'new_pair_baseline':m.score(base,new,'tps')};save(R/'accuracy-summary.json',a)
print(json.dumps({'first':first['physical_tps13'],'baseline':first['accepted_baseline_tps']['rms_ground_m'],'cumulative':{k:v for k,v in a['physical_tps13'].items() if k!='points'},'pair':a['new_pair_tps13']['rms_ground_m']},indent=2))
