import Foundation
import GeoCore
import MapCatalog
import Testing

@testable import NSDataServices

@Suite("Mapped feature queries")
struct MappedFeatureQueryTests {
    /// NSTDB roads and water are Province-restricted, so every query here
    /// needs clearance. Reachable only inside the module, which is the point.
    private static let cleared = ProvinceLicenceClearance(allowsRestrictedLayers: true)

    /// A square, counter-clockwise, closed — GeoJSON's winding for an outer ring.
    private static let outerRing: PolygonHitTest.Ring = [
        GeoPoint(lat: 44.6, lng: -63.5),
        GeoPoint(lat: 44.6, lng: -63.4),
        GeoPoint(lat: 44.7, lng: -63.4),
        GeoPoint(lat: 44.6, lng: -63.5),
    ]

    private static let hole: PolygonHitTest.Ring = [
        GeoPoint(lat: 44.62, lng: -63.48),
        GeoPoint(lat: 44.62, lng: -63.46),
        GeoPoint(lat: 44.64, lng: -63.46),
        GeoPoint(lat: 44.62, lng: -63.48),
    ]

    @Test func everyRoadSublayerIsAskedTwiceAndEveryWaterSublayerOnce() throws {
        let requests = try MappedFeatureQuery.requests(
            for: [[Self.outerRing]], clearance: Self.cleared
        )

        #expect(requests.count == 22)
        // Intersecting roads first, then adjacent, then water. The order is not
        // cosmetic: `unique` keeps the first spelling of a repeated feature, so
        // a road that crosses the parcel must be seen crossing it before it is
        // seen merely passing nearby.
        #expect(requests.prefix(8).allSatisfy { $0.relationship == .intersects })
        #expect(requests.dropFirst(8).prefix(8).allSatisfy { $0.relationship == .adjacent })
        #expect(requests.suffix(6).allSatisfy { $0.layer.layerID == .waterFeatures })
    }

    @Test func aRequestGoesToTheSublayerOfTheServiceTheMapDraws() throws {
        let requests = try MappedFeatureQuery.requests(
            for: [[Self.outerRing]], clearance: Self.cleared
        )
        let roads = try #require(LayerCatalog.descriptor(for: .roads)?.serviceURL)
        let bridge = try #require(requests.first { $0.layer.sublayer == 5 })

        // Derived from the catalog rather than compared to a literal: the point
        // is that the evidence and the drawn layer cannot end up on different
        // hosts, which a literal here would stop detecting.
        #expect(bridge.url.absoluteString == "\(roads.absoluteString)/5/query")
    }

    @Test func theRequestBodyIsTheWebsByteForByte() throws {
        // Generated by running the web's own `URLSearchParams` and
        // `JSON.stringify` over the same rings, not transcribed from reading
        // the source. A captured request from the browser and one from the
        // phone have to be the same string, or comparing two bug reports means
        // re-deriving both.
        let expected = "f=json&where=1%3D1&geometry=%7B%22rings%22%3A%5B%5B%5B-63.5%2C44.6%5D%2C%5B-63.4%2C44.7%5D%2C%5B-63.4%2C44.6%5D%2C%5B-63.5%2C44.6%5D%5D%2C%5B%5B-63.48%2C44.62%5D%2C%5B-63.46%2C44.64%5D%2C%5B-63.46%2C44.62%5D%2C%5B-63.48%2C44.62%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPolygon&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=FEAT_DESC%2CSTREET%2CRTE_NO%2CROADC_DESC&returnGeometry=false"

        let requests = try MappedFeatureQuery.requests(
            for: [[Self.outerRing, Self.hole]], clearance: Self.cleared
        )
        let bridge = try #require(
            requests.first { $0.layer.sublayer == 5 && $0.relationship == .intersects }
        )

        #expect(bridge.body == expected)
    }

    @Test func askingWhatIsNearbyCarriesTheDistanceAndAskingWhatCrossesDoesNot() throws {
        let requests = try MappedFeatureQuery.requests(
            for: [[Self.outerRing]], clearance: Self.cleared
        )
        let crossing = try #require(
            requests.first { $0.layer.sublayer == 8 && $0.relationship == .intersects }
        )
        let nearby = try #require(
            requests.first { $0.layer.sublayer == 8 && $0.relationship == .adjacent }
        )

        #expect(nearby.body.hasSuffix("&distance=20&units=esriSRUnit_Meter"))
        #expect(crossing.body.contains("distance") == false)
        // The 20 m screening distance is a parity constant, not a preference:
        // change it and the two surfaces disagree about which roads reach a
        // property.
        #expect(MappedFeatureQuery.adjacentRoadDistanceMetres == 20)
    }

    @Test func ringsAreTurnedAroundForArcGIS() {
        // GeoJSON winds outer rings counter-clockwise; ArcGIS reads clockwise.
        // Sending them unreversed would ask the service about a polygon wound
        // inside out — which ArcGIS reads as a hole, so the query would be
        // about everything *except* the parcel.
        let rings = MappedFeatureQuery.arcGISRings(from: [[Self.outerRing]])

        #expect(rings.count == 1)
        #expect(rings[0] == Array(Self.outerRing.reversed()))
    }

    @Test func aHoleIsSentAsARingOfItsOwn() {
        // Reversing each ring converts the outer ring and the hole in one step,
        // because it is the winding that tells ArcGIS which is which. So they
        // can travel as a flat list.
        let rings = MappedFeatureQuery.arcGISRings(from: [[Self.outerRing, Self.hole]])

        #expect(rings.count == 2)
        #expect(rings[1] == Array(Self.hole.reversed()))
    }

    @Test func aParcelWithNoBoundaryIsRefusedRatherThanAnsweredWithNothing() {
        // The web returns an empty context here, which renders the same as a
        // parcel with nothing mapped on it. Those are different: one was asked
        // and one never could be. Refusing is what lets the inspector say the
        // outline is missing instead of implying no road touches the property.
        #expect(throws: MappedFeatureQuery.Refusal.noBoundary) {
            try MappedFeatureQuery.requests(for: [], clearance: Self.cleared)
        }
    }

    @Test func anUnansweredLicenceStopsTheRequestBeforeItIsBuilt() {
        // NSTDB roads and water are the same Province-restricted services the
        // map draws, so the evidence query answers to the same licence the
        // layer switches do — and it refuses before it assembles anything,
        // leaving no restricted address lying around as a value.
        #expect(throws: MappedFeatureQuery.Refusal.licenceNotAccepted) {
            try MappedFeatureQuery.requests(for: [[Self.outerRing]], clearance: .none)
        }
    }
}
