"""Freeze physical V04 promotion; preserve all twelve prior controls and failures."""
from pathlib import Path
import json,hashlib,datetime,copy
D=Path(__file__).resolve().parent;P=D.parent
if (D/'repair-freeze.json').exists():raise SystemExit('Frozen experiment exists; use a new directory.')
r=lambda p:json.loads(p.read_text());h=lambda p:hashlib.file_digest(p.open('rb'),'sha256').hexdigest();w=lambda n,v:(D/n).write_text(json.dumps(v,indent=2)+'\n')
f=r(P/'repaired-fit.json');old=copy.deepcopy(f['points']);v=r(P/'validation.json');s=r(P/'validation-scores.json');op=next(p for p in v['points'] if p['id']=='V04');p=copy.deepcopy(op)
p.update(id='C15',role='control',status='Personally re-inspected original unrotated native close/wide crosshair against modern topology; promoted without moving coordinates.',promotion={'old_point':op,'old_result':next(p for p in s['points'] if p['id']=='V04'),'old_fit_sha256':s['fit_sha256'],'reason':'Western tributary below the Stillwater bend: main stem loops from northeast, western tributary joins before the downstream southwest reach; subsequent western junction downstream and eastern branch above corroborate ordering. Recorded 20 px native uncertainty retained.','status':'Permanently diagnostic, never fresh again.'});f['points'].append(p);assert f['points'][:12]==old
f['status']='Provisional thirteen-control TPS; all twelve prior controls preserved. Whole-sheet acceptance false.';w('repaired-fit.json',f)
w('repair-freeze.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fit_sha256':h(D/'repaired-fit.json'),'prior_fit_sha256':h(P/'repaired-fit.json'),'source_sha256':h(Path.home()/'Downloads/fletcher-sheet10/native/sheet10.png'),'boundary_sha256':h(P/'boundary.json'),'control_count':13,'fresh_validation_collected':False,'criteria':{'median_ground_m_max':100,'worst_ground_m_max':200,'distributed_whole_raster_and_seams_required':True}})
d=r(P/'repair-diagnostic.json');d['points'] += [p for p in v['points'] if p['id']!='V04'];d.update(fit_sha256=h(D/'repaired-fit.json'),purpose='Three reused diagnostics. Q02 and V01 retain identity/geometry uncertainty.');w('reused-checks.json',d)
w('identity-audit.json',{'reviewed_before_repair':[f'prior-{scale}/sheet-10-{id}.jpg' for id in ['V01','V04','Q02'] for scale in ['close','wide']],'V04':'Promoted unchanged to C15 after original native/modern branch-order review. Prior 515.04 m error preserved.','V01':'Not promoted: native eastern arm has a nearby southeastern fork while modern tributary hierarchy and separation from western Camp confluence do not yet support precise identity strongly enough. Retain old coordinates and 556.37 m failure as uncertain reused diagnostic.','Q02':'Not promoted: modern braided/pond bank geometry versus native main channel and parallel eastern strokes requires additional interpretation. Preserve unchanged reused diagnostic.','boundary':'Complete native overview personally inspected; Bentinck northeast notch/labels and southern St Anns point remain intact.'})
