from pathlib import Path
import json,hashlib,datetime,shutil,importlib.util
from shapely.geometry import MultiPoint,Point
from tools.church.gcps import GroundControlPoint,load_gcps
R=Path('reports/church/richmond-interior-validation-20260916');assert not R.exists();R.mkdir();(R/'observations').mkdir();(R/'search-evidence').mkdir();C=Path('/Users/dfakkeldy/Downloads/church-richmond-interior-validation-20260916');P=Path('reports/church/richmond-south-seam-20260915')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
f={'input_commit':'5b2c963867bb2bd628ec5e5433a66e6a0ef1c68a','method':'affine','working_rms_ground_m':250,'stretch_rms_ground_m':200,'inputs':{}}
for key,p in [('controls',P/'richmond-controls.csv'),('prior_inventory',P/'richmond-cumulative-validation.csv'),('prior_accuracy',P/'accuracy-summary.json'),('selection_freeze',Path('reports/church/coverage-20260914/richmond/affine14-freeze.json')),('baseline_controls',Path('reports/church/physical-review-20260912/richmond/refinement-04/frozen-fit.csv')),('diagnostics',Path('reports/church/coverage-20260914/richmond/affine14-diagnostic-review.csv'))]:f['inputs'][key]={'path':str(p),'sha256':sha(p)}
f.update(raster='/Users/dfakkeldy/Downloads/church-coverage-20260914/richmond-affine14/richmond-affine14-20m.tif',raster_sha256='c44fd27bf527f468a779a7b37218ab402b5bf306c9a3b9cae5bb8769eba15fd0',scope='Fresh western-interior check against unchanged Richmond affine14; all preceding first results retained');save(R/'freeze.json',f);shutil.copy2(P/'richmond-controls.csv',R/'controls.csv')
q=json.loads((C/'buchanan-shared-junctions.json').read_text())[0];src=C/'buchanan-native.jpg';ref=Path('/Users/dfakkeldy/Downloads/church-georeferencing-20260912/reference/water-lines.geojson');o={'id':'R56','label':'Buchanan Lake northwestern lake/stream junction','role':'check','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_frame':json.loads((C/'buchanan-frame.json').read_text()),'source_crop_path':str(src),'source_crop_sha256':sha(src),'source_sha256':'462194ca1ca810d88416d7cd344f17c5f37acf20c8e43381dc3064668010a5f7','source_display_pixel_xy':[527,543],'pixel_xy':[9327,15443],'lonlat':q['lonlat'],'reference_path':str(ref),'reference_sha256':sha(ref),'reference_vertices':[q['river'],*q['lake']],'uncertainty_ground_m':180,'point_definition':'Northwestern stream meets the upper-west lake shore, distinct from the separate western connection farther south.','identity_evidence':'The long east-west Buchanan basin, separate northwest and west water connections, northern/eastern tributaries and road along the north side distinguish the feature. The native crop resolves the upper-west shoreline turn and the northwest approach, with a short ink gap at their convergence. The lower west connection is a different node. Modern original WARV50 and WALK20 segments share the selected coordinate. The lake name identifies locality only; neither the namepoint nor a whole-basin centroid was used. McIntyre Lake and its earlier R31 junction are separate features to the west.','phase':'Untouched fresh physical validation after the affine14 freeze; excluded from fitting and model selection'};save(R/'observations/R56.json',o)
for a,b in [('buchanan-proposal.jpg','R56-native-review.jpg'),('buchanan-proposal-detail.jpg','R56-native-enlarged.jpg'),('buchanan-reference-proposal.jpg','R56-reference-review.jpg')]:shutil.copy2(C/a,R/'observations'/b)
for p in C.iterdir():
 if p.suffix in ['.py','.json','.jpg','.geojson']:shutil.copy2(p,R/'search-evidence'/p.name)
save(R/'search-evidence/source-verification.json',{'observed_at':o['recorded_at'],'method':'Remote sha256sum of the original archival Richmond TIFF during this continuation','source':o['source_frame']['source'],'sha256':o['source_sha256'],'dimensions':[35735,30429]})
save(R/'search-evidence/withheld.json',{'black_river':'Candidate tributary-to-main-junction correspondence was not securely distinguished from road crossings and adjacent ink in the source. No observation or score adopted.','rae_brook':'A unique shared source junction was not established from the faint drainage and nearby named cove/settlement geometry. No observation or score adopted.','false_bay_lake':'The drawn outline did not yield a secure modern basin correspondence. A bounded source query returned104 original features, all already present with unchanged geometry in the earlier cache. No match or score adopted; this is not evidence that water is absent.','buchanan_whole_centroid':'Not used. The precise northwest lake/stream node was selected instead of reconstructing the full southern shoreline beside lettering.'})
cs=load_gcps(R/'controls.csv');prior=[p for p in load_gcps(P/'richmond-cumulative-validation.csv') if p.role=='check'];base=[p for p in load_gcps(Path(f['inputs']['baseline_controls']['path'])) if p.role=='control'];p=GroundControlPoint(*o['pixel_xy'],*o['lonlat'],'check','R56');s=importlib.util.spec_from_file_location('score',R.parent/'target-refinement-20260913/score_models.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
first={'scored_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observation_sha256':sha(R/'observations/R56.json'),'freeze_sha256':sha(R/'freeze.json'),'inside_control_hull':MultiPoint([(q.pixel_x,q.pixel_y) for q in cs]).convex_hull.covers(Point(*o['pixel_xy'])),'affine14':m.score(cs,[p],'affine'),'v4_same_feature':m.score(base,[p],'tps')};save(R/'R56-first.json',first);row=f'{p.pixel_x},{p.pixel_y},{p.lon},{p.lat},check,R56\n';(R/'fresh-validation.csv').write_text((P/'richmond-cumulative-validation.csv').read_text()+row);(R/'new-check.csv').write_text((P/'richmond-controls.csv').read_text()+row);a={'affine14':m.score(cs,prior+[p],'affine'),'v4_same_checks':m.score(base,prior+[p],'tps')};save(R/'accuracy-summary.json',a);print(json.dumps({'first':first,'cumulative':{k:v for k,v in a['affine14'].items() if k!='points'}},indent=2))
